import test from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import { once } from 'node:events';
import type { Database, RechargeOrder, ModelConfig } from './types.js';
import { activateKeyMembership, activePeriod, grantMembership, membershipSummary, monthAnniversary, products, publishCatalog, recordKeySale, trialCatalog } from './memberships.js';
import { availablePowerMicros, chargePower, reservePower, releasePower } from './powerBilling.js';
import { preparePayment, settlePayment } from './payments.js';
import { reconcileInterruptedBilling, runBilledModel } from './modelBilling.js';
import { installMembershipRoutes } from './membershipRoutes.js';
function fixture(){return {users:[{id:'a',enabled:true,role:'admin'},{id:'b',enabled:true}],workspaces:[{id:'wa',status:'active'},{id:'wb',status:'active'}],workspaceMembers:[{workspaceId:'wa',userId:'a'},{workspaceId:'wb',userId:'b'}],powerAccounts:[{id:'pa',workspaceId:'wa',userId:'a',balanceMicros:10e6,paidBalanceMicros:10e6},{id:'pb',workspaceId:'wb',userId:'b',balanceMicros:0}],settings:{rechargeCnyPerPower:7,membershipBilling:{...trialCatalog,enabled:true}},rechargeOrders:[],powerLedger:[],auditLogs:[],modelUsageRecords:[],oneKeyDevices:[],models:[]} as unknown as Database;}
const scope={workspaceId:'wa',userId:'a'};
function order(db:Database,id:string,productId='standard-monthly'){const result={...scope,id,product:products(db.settings.membershipBilling!).find(p=>p.id===productId)!,status:'paid',requestedMicros:0} as RechargeOrder;db.rechargeOrders.push(result);return result;}
function remote(o:RechargeOrder){return {out_trade_no:o.id,trade_state:'SUCCESS',appid:'app',mchid:'merchant',amount:{total:o.payment!.amountFen,currency:'CNY'},transaction_id:`txn-${o.id}`};}
test('trial prices, 20% OFF and monthly allocations match agreed figures',()=>{const p=products(trialCatalog);assert.deepEqual(p.map(v=>[v.id,v.amountFen,v.monthlyMicros,v.months]),[['standard-monthly',9900,20e6,1],['standard-annual',95040,20e6,12],['standard-key',99900,20e6,3],['premium-monthly',29900,70e6,1],['premium-annual',287040,70e6,12],['premium-key',129900,70e6,3]]);});
test('calendar months clamp independently, including leap years',()=>{assert.equal(new Date(monthAnniversary(Date.parse('2026-01-31T05:30:00Z'),1)).toISOString(),'2026-02-28T05:30:00.000Z');assert.equal(new Date(monthAnniversary(Date.parse('2026-01-31T05:30:00Z'),2)).toISOString(),'2026-03-31T05:30:00.000Z');assert.equal(new Date(monthAnniversary(Date.parse('2024-01-31T05:30:00Z'),1)).toISOString(),'2024-02-29T05:30:00.000Z');});
test('annual allowance is twelve monthly periods; unused quota expires, wallet is preserved',()=>{const db=fixture(),at=Date.parse('2026-01-31T05:00:00Z');grantMembership(db,order(db,'annual','standard-annual'),at);assert.equal(db.powerAccounts[0].membershipPeriods!.length,12);assert.equal(membershipSummary(db,scope,at).active?.remainingPercent,100);db.powerAccounts[0].membershipPeriods![0].remainingMicros=1e6;assert.equal(membershipSummary(db,scope,monthAnniversary(at,1)).active?.remainingPercent,100);assert.equal(membershipSummary(db,scope,monthAnniversary(at,12)).active,null);assert.equal(db.powerAccounts[0].balanceMicros,10e6);});
test('renewal queues, grant replay is harmless, no early quota refill',()=>{const db=fixture(),at=Date.now();const first=order(db,'one');grantMembership(db,first,at);db.powerAccounts[0].membershipPeriods![0].remainingMicros=3e6;grantMembership(db,first,at+1);grantMembership(db,order(db,'two'),at+1000);assert.equal(db.powerAccounts[0].membershipPeriods!.length,2);assert.equal(membershipSummary(db,scope,at+1001).active?.remainingPercent,15);assert.equal(db.powerAccounts[0].membershipPeriods![1].startsAt,db.powerAccounts[0].membershipPeriods![0].endsAt);});
test('premium pauses standard remaining time and consumed allowance, then resumes it',()=>{const db=fixture(),at=Date.parse('2026-06-01T00:00:00Z');grantMembership(db,order(db,'low'),at);const low=db.powerAccounts[0].membershipPeriods![0],oldEnd=Date.parse(low.endsAt),upgrade=at+20*86400000;low.remainingMicros=4e6;grantMembership(db,order(db,'high','premium-monthly'),upgrade);const high=db.powerAccounts[0].membershipPeriods![1],end=Date.parse(high.endsAt);assert.equal(membershipSummary(db,scope,upgrade).active?.tier,'premium');assert.equal(Date.parse(low.endsAt)-end,oldEnd-upgrade);assert.equal(membershipSummary(db,scope,end).active?.remainingPercent,20);assert.equal(membershipSummary(db,scope,end).active?.tier,'standard');});
test('reservations settle from their original month after expiration and restart',()=>{const db=fixture(),at=Date.now();grantMembership(db,order(db,'months','standard-annual'),at-1000);reservePower(db,{...scope,amountMicros:5e6,holdId:'request'});const old=db.powerAccounts[0].membershipPeriods![0];old.endsAt=new Date(at-1).toISOString();const next=db.powerAccounts[0].membershipPeriods![1];next.startsAt=new Date(at-1).toISOString();db.modelUsageRecords.push({id:'request',...scope,reservedMicros:5e6,status:'pending'} as any);const restored=JSON.parse(JSON.stringify(db)) as Database;reconcileInterruptedBilling(restored);assert.equal(availablePowerMicros(restored,'wa','a'),30e6);chargePower(restored,{...scope,amountMicros:2e6,holdId:'request',usageRecordId:'request',modelId:'m',title:'test'});assert.equal(restored.powerAccounts[0].membershipPeriods![0].remainingMicros,18e6);assert.equal(restored.powerAccounts[0].membershipPeriods![1].remainingMicros,20e6);assert.equal(restored.powerAccounts[0].balanceMicros,10e6);assert.equal(restored.powerAccounts[0].reservedMicros,0);});
test('member quota first, paid balance second; parallel holds cannot overspend',()=>{const db=fixture(),at=Date.now();grantMembership(db,order(db,'m'),at);reservePower(db,{...scope,amountMicros:25e6,holdId:'r'});assert.equal(availablePowerMicros(db,'wa','a'),5e6);assert.throws(()=>reservePower(db,{...scope,amountMicros:6e6,holdId:'r2'}),/不足/);chargePower(db,{...scope,amountMicros:22e6,holdId:'r',usageRecordId:'r',modelId:'m',title:'test'});assert.equal(db.powerAccounts[0].balanceMicros,8e6);assert.equal(db.powerLedger[0].membershipMicros,20e6);assert.equal(db.powerLedger[0].paidPrincipalMicros,2e6);assert.equal(db.powerAccounts[1].balanceMicros,0);});
test('failed held call restores quota without extending or refreshing it',()=>{const db=fixture();grantMembership(db,order(db,'m'));reservePower(db,{...scope,amountMicros:4e6,holdId:'r'});releasePower(db,{...scope,amountMicros:4e6,holdId:'r'});assert.equal(activePeriod(db.powerAccounts[0])!.remainingMicros,20e6);assert.equal(availablePowerMicros(db,'wa','a'),30e6);});
test('payment amount and entitlement snapshots are immutable; callbacks are idempotent',()=>{const db=fixture(),intent={productId:'standard-annual'},config={appId:'app',mchId:'merchant'},op='membership-test-operation';const prepared=preparePayment(db,scope,op,intent,config);publishCatalog(db,'a',{standardMonthlyMicros:1e6,standardMonthlyFen:10000,enabled:false});assert.equal(preparePayment(db,scope,op,intent,config).order.payment!.amountFen,95040);assert.throws(()=>settlePayment(db,{...remote(prepared.order),amount:{total:1,currency:'CNY'}}),/不匹配/);settlePayment(db,remote(prepared.order));settlePayment(db,remote(prepared.order));assert.equal(db.powerAccounts[0].membershipPeriods!.length,12);assert.equal(db.powerAccounts[0].membershipPeriods![0].grantedMicros,20e6);assert.equal(db.powerAccounts[0].balanceMicros,10e6);assert.throws(()=>preparePayment(db,scope,op,{productId:'premium-annual'},config),/不一致/);});
test('topups use fixed 7 CNY, preserve old balances, never extend membership',()=>{const db=fixture();db.settings.rechargeCnyPerPower=9;const o=preparePayment(db,scope,'topup-operation-123',{amountFen:3000},{appId:'app',mchId:'merchant'}).order;assert.equal(o.requestedMicros,4285714);settlePayment(db,remote(o));assert.equal(db.powerAccounts[0].balanceMicros,14285714);assert.equal(db.powerAccounts[0].membershipPeriods,undefined);});
test('Key purchase activates after exact-device delivery, not at payment; repeated activation preserves term',()=>{const db=fixture(),o=preparePayment(db,scope,'key-order-operation',{productId:'premium-key'},{appId:'app',mchId:'merchant'}).order;settlePayment(db,remote(o));assert.equal(db.powerAccounts[0].membershipPeriods,undefined);assert.throws(()=>activateKeyMembership(db,scope,o.id),/未交付/);const saved=db.rechargeOrders[0];saved.fulfilledDeviceId='device';db.oneKeyDevices.push({id:'device',...scope,status:'active'} as any);activateKeyMembership(db,scope,o.id,Date.parse('2026-12-01T00:00:00Z'));activateKeyMembership(db,scope,o.id,Date.parse('2026-12-02T00:00:00Z'));assert.equal(db.powerAccounts[0].membershipPeriods!.length,3);assert.equal(db.powerAccounts[0].membershipPeriods![0].startsAt,'2026-12-01T00:00:00.000Z');assert.throws(()=>activateKeyMembership(db,{workspaceId:'wb',userId:'b'},o.id),/未交付/);});
test('manual first-Key sale records verified receipt once with no premature credit',()=>{const db=fixture(),input={...scope,operationId:'offline-order-123456',productId:'standard-key',paymentReference:'bank-reference-123'};recordKeySale(db,'a',input);recordKeySale(db,'a',input);assert.equal(db.rechargeOrders.length,1);assert.equal(db.powerAccounts[0].membershipPeriods,undefined);assert.equal(db.powerAccounts[0].balanceMicros,10e6);assert.throws(()=>recordKeySale(db,'b',input),/管理员/);assert.throws(()=>recordKeySale(db,'a',{...input,operationId:'another-order-1234'}),/已入账/);});
test('membership access rejects forged workspace, disabled membership and enterprise billing',()=>{const db=fixture();assert.throws(()=>membershipSummary(db,{workspaceId:'wb',userId:'a'}),/不可用/);assert.throws(()=>preparePayment(db,{workspaceId:'wb',userId:'a'},'forged-operation-id',{productId:'standard-monthly'},{appId:'app',mchId:'merchant'}),/不可用/);db.workspaceMembers[0].status='disabled';assert.throws(()=>grantMembership(db,order(db,'bad')),/不可用/);});
test('actual model lifecycle consumes monthly allowance, frozen .6 price is not discounted again',async()=>{const db=fixture();grantMembership(db,order(db,'m'));const model={id:'model',kind:'chat',name:'test',enabled:true,inputPowerPerMillion:6,outputPowerPerMillion:12,costInputPowerPerMillion:1,costOutputPowerPerMillion:2,pricing:{version:1,label:'优惠期 ×0.6',multiplier:.6,referenceInput:10,referenceOutput:20,publishedAt:new Date().toISOString()}} as ModelConfig;db.models.push(model);await runBilledModel({read:async()=>db,mutate:async fn=>fn(db)},{...scope,model,input:'hello',activity:'test',requestId:'request'},async()=>({usage:{inputTokens:1000,outputTokens:1000,totalTokens:2000,source:'provider'}}));assert.equal(db.powerLedger[0].membershipMicros,18000);assert.equal(db.powerAccounts[0].balanceMicros,10e6);assert.equal(db.modelUsageRecords[0].costMicros,3000);assert.equal(db.powerAccounts[0].powerHolds!.length,0);});
test('HTTP membership scope ignores browser workspace and admin endpoints require admin auth',async t=>{const db=fixture(),app=express();app.use(express.json());const auth=(req:any,res:any,next:any)=>{if(req.headers.authorization!=='user')return res.sendStatus(401);req.user={id:'a'};req.workspaceId='wa';next();};const admin=(_req:any,res:any)=>res.sendStatus(403);installMembershipRoutes(app,[auth],[admin],{read:async()=>db,mutate:async fn=>fn(db)});const server=app.listen(0,'127.0.0.1');await once(server,'listening');t.after(()=>{server.closeAllConnections();server.close();});const base=`http://127.0.0.1:${(server.address() as any).port}`;assert.equal((await fetch(`${base}/api/me/membership`)).status,401);const reply=await(await fetch(`${base}/api/me/membership?workspaceId=wb&userId=b`,{headers:{authorization:'user'}})).json() as any;assert.equal(reply.purchasedBalanceCny,70);assert.equal((await fetch(`${base}/api/admin/membership`)).status,403);const fail=await fetch(`${base}/api/me/membership/activate`,{method:'POST',headers:{authorization:'user','content-type':'application/json'},body:JSON.stringify({workspaceId:'wb',userId:'b',orderId:'foreign'})});assert.equal(fail.status,400);});

test('monthly boundaries follow China calendar near UTC day boundary',()=>{assert.equal(new Date(monthAnniversary(Date.parse('2026-01-30T16:00:00Z'),1)).toISOString(),'2026-02-27T16:00:00.000Z');assert.equal(new Date(monthAnniversary(Date.parse('2026-01-30T16:00:00Z'),2)).toISOString(),'2026-03-30T16:00:00.000Z');});

test('publishing membership trial fixes recharge conversion and preserves paid wallet principal',()=>{const db=fixture();db.settings.rechargeCnyPerPower=9;publishCatalog(db,'a',{enabled:true});assert.equal(db.settings.rechargeCnyPerPower,7);assert.equal(db.powerAccounts[0].balanceMicros,10e6);assert.equal(db.powerAccounts[0].paidBalanceMicros,10e6);});


test('first successful Key login activates delivered bundle once',async()=>{
  const db=fixture(),{OneKeyService}=await import('./oneKeyService.js'),{default:crypto}=await import('node:crypto');
  const sale=recordKeySale(db,'a',{...scope,operationId:'login-key-sale-123456',productId:'standard-key',paymentReference:'receipt-login-test'});
  db.oneKeyDevices.push({id:'device',...scope,status:'active'} as any);sale.fulfilledDeviceId='device';
  db.oneTimeLoginCodes=[{id:'code-id',tokenHash:crypto.createHash('sha256').update('login-code').digest('base64url'),deviceId:'device',installationId:'computer-a-'+ '1'.repeat(32),...scope,expiresAt:new Date(Date.now()+60000).toISOString(),createdAt:new Date().toISOString()}];
  const service=new OneKeyService({read:async()=>db,mutate:async fn=>fn(db)});
  const login=await service.redeem('login-code');assert.equal(login.userId,'a');assert.equal(db.powerAccounts[0].membershipPeriods!.length,3);assert.equal(membershipSummary(db,scope).active?.tier,'standard');assert.equal(db.powerAccounts[0].balanceMicros,10e6);
  await assert.rejects(()=>service.redeem('login-code'),/已使用/);assert.equal(db.powerAccounts[0].membershipPeriods!.length,3);
});

test('company wallets remain independent of personal memberships and packages',()=>{
 const db=fixture();db.workspaces[0].kind='company';assert.throws(()=>membershipSummary(db,scope),/企业/);assert.throws(()=>grantMembership(db,order(db,'company')),/企业/);assert.throws(()=>preparePayment(db,scope,'company-order-123456',{productId:'premium-monthly'},{appId:'app',mchId:'merchant'}),/企业/);assert.equal(db.powerAccounts[0].membershipPeriods,undefined);
});
