import test from "node:test";
import assert from "node:assert/strict";
import { once } from "node:events";
import { createServer } from "node:http";
import fs from "node:fs/promises";
import os from "node:os";
import path from "node:path";
import express from "express";
import type { Database } from "./types.js";
import type { Store } from "./db.js";
import { AttachmentService } from "./attachmentService.js";
import { installPublicSharingRoutes } from "./publicSharingRoutes.js";

test("real HTTP public flow: Key-managed publication, isolated uploads, paid question, durable receipt and close",async t=>{
  const directory=await fs.mkdtemp(path.join(os.tmpdir(),"one-public-test-"));
  t.after(()=>fs.rm(directory,{recursive:true,force:true}));
  let modelCalls=0;
  const gateway=createServer(async(req,res)=>{let body="";for await(const chunk of req)body+=chunk;modelCalls++;assert.match(body,/PRIVATE_ATTACHMENT_MARKER/);assert.doesNotMatch(body,/OWNER_PRIVATE_CHAT/);assert.equal(JSON.parse(body).tools,undefined);res.setHeader("Content-Type","application/json");res.end(JSON.stringify({choices:[{message:{content:"Fixture grounded answer"},finish_reason:"stop"}],usage:{prompt_tokens:40,completion_tokens:20,total_tokens:60}}));});
  gateway.listen(0,"127.0.0.1");await once(gateway,"listening");t.after(()=>{gateway.closeAllConnections();gateway.close();});
  let db={users:[{id:"owner",enabled:true},{id:"other",enabled:true}],workspaces:[{id:"ws",status:"active"},{id:"other-ws",status:"active"}],workspaceMembers:[{workspaceId:"ws",userId:"owner",role:"owner"},{workspaceId:"other-ws",userId:"other",role:"owner"}],models:[{id:"model",name:"Fixture model",enabled:true,kind:"chat",apiKey:"MODEL_SECRET",protocol:"openai",model:"fixture",baseUrl:`http://127.0.0.1:${(gateway.address() as any).port}`,systemPrompt:"",inputPowerPerMillion:1,outputPowerPerMillion:1,costInputPowerPerMillion:1,costOutputPowerPerMillion:1}],settings:{safetyRules:"safe",rechargeCnyPerPower:7},auditLogs:[],attachments:[],knowledgeConnections:[],messages:[{content:"OWNER_PRIVATE_CHAT"}],modelUsageRecords:[],powerLedger:[],powerAccounts:[{id:"power",workspaceId:"ws",userId:"owner",balanceMicros:100e6,reservedMicros:0}]} as unknown as Database;
  const store:Store={read:async()=>db,mutate:async fn=>{const before=structuredClone(db);try{return fn(db);}catch(e){db=before;throw e;}}};
  const service=new AttachmentService(store,directory),app=express();app.use(express.json());
  installPublicSharingRoutes(app,[(req,res,next)=>{if(req.headers["x-key"]!=="present"){res.sendStatus(428);return;}const other=req.headers["x-user"]==="other";req.user={id:other?"other":"owner"} as any;req.workspaceId=other?"other-ws":"ws";next();}],store,{recallWithDiagnostics:async(_w:string,_q:string,_k:number,ids:string[])=>{assert.deepEqual(ids,[]);return {chunks:[],failures:[],status:"not_connected"};}} as any,service);
  const server=app.listen(0,"127.0.0.1");await once(server,"listening");t.after(()=>{server.closeAllConnections();server.close();});
  const base=`http://127.0.0.1:${(server.address() as any).port}/api/sharing`;
  const owner={"x-key":"present","Content-Type":"application/json"};
  assert.equal((await fetch(base+"/manage")).status,428);
  assert.equal((await(await fetch(base+"/manage",{headers:owner})).json()).ready,false);
  db.publications=[];db.publicSessions=[];db.publicRuns=[];
  const pub=await(await fetch(base+"/manage",{method:"POST",headers:owner,body:JSON.stringify({name:"Share fixture",description:"Question answering",prompt:"PRIVATE_PROMPT",modelId:"model",sourceIds:[],attachments:true,budget:10,perRun:1,days:7,confirmed:true,workspaceId:"other-ws",tools:["run_command"]})})).json();
  assert.ok(pub.slug);const url=base+"/"+pub.slug;
  const metadata=await(await fetch(url)).text();assert.doesNotMatch(metadata,/PRIVATE_PROMPT|MODEL_SECRET|owner|other-ws/);
  const token1=(await(await fetch(url+"/sessions",{method:"POST"})).json()).token;
  const token2=(await(await fetch(url+"/sessions",{method:"POST"})).json()).token;
  const h1={Authorization:`Bearer ${token1}`,"Content-Type":"application/json"},h2={...h1,Authorization:`Bearer ${token2}`};
  const bytes=Buffer.from("PRIVATE_ATTACHMENT_MARKER: documented fact");
  const created=await(await fetch(url+"/uploads",{method:"POST",headers:h1,body:JSON.stringify({name:"notes.txt",size:bytes.length,mimeType:"text/plain"})})).json();
  const fileId=created.attachment.id;assert.ok(fileId);assert.doesNotMatch(JSON.stringify(created),/storagePath|extractedText/);
  assert.notEqual((await fetch(url+`/uploads/${fileId}`,{headers:h2})).status,200);
  assert.notEqual((await fetch(url+`/uploads/${fileId}/chunks?offset=0`,{method:"PUT",headers:{...h2,"Content-Type":"application/octet-stream"},body:bytes})).status,200);
  assert.equal(db.attachments[0].uploadedBytes,0);
  assert.equal((await fetch(url+`/uploads/${fileId}/chunks?offset=0`,{method:"PUT",headers:{...h1,"Content-Type":"application/octet-stream"},body:bytes})).status,200);
  assert.equal((await fetch(url+`/uploads/${fileId}/complete`,{method:"POST",headers:h1})).status,200);
  for(let i=0;i<100&&db.attachments[0].status!=="ready";i++)await new Promise(r=>setTimeout(r,50));
  assert.equal(db.attachments[0].status,"ready");
  const payload={content:"QUESTION_PRIVATE: what does the file say?",operationId:"http_operation_1234",attachmentIds:[fileId],tools:["run_command"]};
  assert.notEqual((await fetch(url+"/questions",{method:"POST",headers:h2,body:JSON.stringify(payload)})).status,202);
  const response=await fetch(url+"/questions",{method:"POST",headers:h1,body:JSON.stringify(payload)});assert.equal(response.status,202);const receipt=(await response.json()).run;
  let answer:any;
  for(let i=0;i<100;i++){answer=await(await fetch(url+`/questions/${receipt.id}`,{headers:h1})).json();if(answer.run.status!=="running")break;await new Promise(r=>setTimeout(r,50));}
  assert.equal(answer.run.status,"completed");assert.equal(modelCalls,1);
  const repeated=await fetch(url+"/questions",{method:"POST",headers:h1,body:JSON.stringify(payload)});assert.equal(repeated.status,200);assert.equal(modelCalls,1);
  assert.equal((await fetch(url+`/questions/${receipt.id}`,{headers:h2})).status,404);
  assert.equal((await fetch(url+`/questions/${receipt.id}`,{headers:owner})).status,401);
  const usage=await(await fetch(base+`/manage/${pub.id}/usage`,{headers:owner})).text();assert.doesNotMatch(usage,/PRIVATE_ATTACHMENT_MARKER|QUESTION_PRIVATE|Fixture grounded answer|tokenHash/);assert.equal(JSON.parse(usage).total,1);
  assert.equal((await fetch(base+`/manage/${pub.id}/usage`,{headers:{...owner,"x-user":"other"}})).status,404);
  assert.equal((await fetch(base+`/manage/${pub.id}/close`,{method:"POST"})).status,428);
  assert.equal((await fetch(base+`/manage/${pub.id}/close`,{method:"POST",headers:owner})).status,200);
  assert.equal((await fetch(url+"/session",{headers:h1})).status,410);
  assert.equal((await fetch(url+"/questions",{method:"POST",headers:h1,body:JSON.stringify({...payload,operationId:"http_operation_9999"})})).status,410);
  assert.equal(modelCalls,1);
});
