import crypto from "node:crypto";
import { Client } from "@modelcontextprotocol/sdk/client/index.js";
import { StreamableHTTPClientTransport } from "@modelcontextprotocol/sdk/client/streamableHttp.js";
import type { Store } from "../db.js";
import { AuthorizationSessions } from "../connectors/authorizationSessions.js";
import { assertAllowedConnectorUrl, readBoundedJson } from "../connectors/securityPolicy.js";
import { uid } from "../security.js";
import type { ConnectorAuthorizationSession, Database, KnowledgeConnection, KnowledgeProviderId } from "../types.js";
import { decryptCredential, encryptCredential, knowledgeCredentialContext } from "./credentialCipher.js";
import type { KnowledgeChunk } from "./provider.js";

type OAuthClient = { clientId: string; clientSecret?: string; tokenAuthMethod: "none" | "client_secret_post" };
type OAuthFlow = OAuthClient & { workspaceId: string; userId: string; connectionId?: string; previousStatus?: KnowledgeConnection["status"]; redirectUri: string; verifier: string };
type TokenResponse = { access_token: string; refresh_token?: string; expires_in?: number; client_id?: string; workspace_id?: string; workspace_name?: string; user_id?: string };
type McpClient = { listTools(): Promise<{ tools: Array<{ name: string }> }>; callTool(params: { name: string; arguments?: Record<string, unknown> }): Promise<unknown>; close(): Promise<void> };
export type RemoteMcpProviderConfig = {
  provider: "flowus";
  label: string;
  mcpUrl: string;
  authorizationUrl: string;
  tokenUrl: string;
  registrationUrl: string;
  revokeUrl?: string;
  hosts: readonly string[];
  sourceHosts: readonly string[];
  scope: string;
  readOnlyTools: readonly string[];
  searchTools: readonly string[];
  fetchTools: readonly string[];
  envPrefix: string;
};
export type RemoteMcpServiceOptions = { fetch?: typeof fetch; createClient?: (accessToken: string) => Promise<McpClient> };

const flowLifetimeMs = 10 * 60 * 1000;
const maxChunkChars = 24_000;
const maxToolTextChars = 256_000;
const timeoutMs = Math.max(3_000, Number(process.env.REMOTE_MCP_TIMEOUT_MS ?? 20_000));

function requiredString(value: unknown, label: string, max = 65_536) { if (typeof value !== "string" || !value || value.length > max) throw new Error(`${label}响应格式无效`); return value; }
function optionalString(value: unknown, label: string, max = 65_536) { return value === undefined || value === null ? undefined : requiredString(value, label, max); }
function tokenResponse(value: unknown, label: string): TokenResponse {
  if (!value || typeof value !== "object" || Array.isArray(value)) throw new Error(`${label}授权响应格式无效`);
  const item = value as Record<string, unknown>;
  const expires = item.expires_in === undefined ? undefined : Number(item.expires_in);
  if (expires !== undefined && (!Number.isFinite(expires) || expires <= 0 || expires > 366 * 24 * 60 * 60)) throw new Error(`${label}授权有效期响应格式无效`);
  return { access_token: requiredString(item.access_token, "访问令牌"), refresh_token: optionalString(item.refresh_token, "刷新令牌"), expires_in: expires, client_id: optionalString(item.client_id, "客户端", 2_000), workspace_id: optionalString(item.workspace_id, "工作空间", 2_000), workspace_name: optionalString(item.workspace_name, "工作空间名称", 500), user_id: optionalString(item.user_id, "用户", 2_000) };
}
async function deadline<T>(operation: Promise<T>, message: string, limit = timeoutMs) { let timer: NodeJS.Timeout | undefined; try { return await Promise.race([operation, new Promise<never>((_, reject) => { timer = setTimeout(() => reject(new Error(message)), limit); })]); } finally { if (timer) clearTimeout(timer); } }
async function closeClient(client: McpClient, label: string) { await deadline(client.close(), `${label} MCP 连接关闭超时`, 2_000).catch(() => undefined); }
function challenge(verifier: string) { return crypto.createHash("sha256").update(verifier).digest("base64url"); }
function textContent(result: unknown) { if (!result || typeof result !== "object") return ""; const blocks = (result as { content?: unknown }).content; if (!Array.isArray(blocks)) return ""; return blocks.map(block => { if (!block || typeof block !== "object") return ""; const item = block as { type?: unknown; text?: unknown }; return item.type === "text" && typeof item.text === "string" ? item.text : ""; }).filter(Boolean).join("\n").slice(0, maxToolTextChars); }
function jsonContent(text: string): unknown { try { return JSON.parse(text); } catch { return undefined; } }
function stringValue(value: unknown, keys: string[]) { if (!value || typeof value !== "object" || Array.isArray(value)) return undefined; const item = value as Record<string, unknown>; for (const key of keys) if (typeof item[key] === "string" && item[key]) return item[key] as string; return undefined; }
function sourceUrl(value: unknown, hosts: readonly string[]) { if (typeof value !== "string" || !value) return undefined; try { const url = new URL(value); return url.protocol === "https:" && hosts.includes(url.hostname) ? url.toString() : undefined; } catch { return undefined; } }
function candidates(value: unknown, hosts: readonly string[]) {
  const found: Array<{ id?: string; title?: string; url?: string; excerpt?: string }> = []; const seen = new Set<unknown>();
  function visit(current: unknown, depth = 0) { if (!current || typeof current !== "object" || seen.has(current) || seen.size > 2_000 || depth > 12) return; seen.add(current); if (Array.isArray(current)) { current.forEach(item => visit(item, depth + 1)); return; } const id = stringValue(current, ["id", "guid", "note_guid", "page_id", "uuid"]); const url = sourceUrl(stringValue(current, ["url", "href", "link"]), hosts); const title = stringValue(current, ["title", "name", "subject"]); const excerpt = stringValue(current, ["highlight", "excerpt", "snippet", "text", "content"]); if ((id || url) && (title || excerpt)) found.push({ id, url, title, excerpt }); Object.values(current as Record<string, unknown>).forEach(item => visit(item, depth + 1)); }
  visit(value); const unique = new Map<string, (typeof found)[number]>(); for (const item of found) unique.set(item.id || item.url || `${item.title}:${item.excerpt}`, item); return [...unique.values()];
}

export class RemoteMcpKnowledgeService {
  private readonly fetcher: typeof fetch; private readonly createClient: (accessToken: string) => Promise<McpClient>; private readonly sessions: AuthorizationSessions; private readonly refreshes = new Map<string, Promise<string>>();
  constructor(private store: Store, private config: RemoteMcpProviderConfig, options: RemoteMcpServiceOptions = {}) {
    this.fetcher = options.fetch || fetch; this.sessions = new AuthorizationSessions(store);
    this.createClient = options.createClient || (async token => { const client = new Client({ name: "ONE", version: "0.1.0" }); const transport = new StreamableHTTPClientTransport(assertAllowedConnectorUrl(config.mcpUrl, config.hosts), { requestInit: { redirect: "error", headers: { Authorization: `Bearer ${token}` } } }); await deadline(client.connect(transport), `${config.label} MCP 连接超时`); return client; });
  }
  private connectionFor(db: Database, workspaceId: string) { return db.knowledgeConnections.find(item => item.workspaceId === workspaceId && item.provider === this.config.provider); }
  private secret(connection: KnowledgeConnection, field: "client_secret" | "access_token" | "refresh_token", encrypted: string) { return decryptCredential(encrypted, knowledgeCredentialContext(connection.workspaceId, this.config.provider, field)); }
  private protect(workspaceId: string, field: "client_secret" | "access_token" | "refresh_token", value: string) { return encryptCredential(value, knowledgeCredentialContext(workspaceId, this.config.provider, field)); }
  private origin(value: string) { const origin = new URL(value).origin; if (process.env.NODE_ENV === "production" && !origin.startsWith("https://")) throw new Error("生产环境的 APP_ORIGIN 必须使用 HTTPS"); return origin; }
  localStatus(db: Database, workspaceId: string) { const connection = this.connectionFor(db, workspaceId); if (!connection || connection.status === "revoked") return { state: "not_connected" as const, code: "AUTHORIZATION_REQUIRED", message: `请连接 ${this.config.label}`, evidence: "stored" as const }; if (connection.status === "pending") return { state: "pending" as const, code: "AUTHORIZATION_PENDING", message: `等待完成 ${this.config.label} 授权`, evidence: "stored" as const }; if (connection.status === "error") return { state: "error" as const, code: "CONNECTION_ERROR", message: `${this.config.label} 连接需要检查`, evidence: "stored" as const }; if (!connection.clientId || !connection.encryptedAccessToken) return { state: "not_connected" as const, code: "CREDENTIAL_UNAVAILABLE", message: `${this.config.label} 授权资料不完整，请重新连接`, evidence: "stored" as const }; return { state: "configured" as const, code: "CREDENTIAL_STORED", message: `已保存 ${this.config.label} 授权`, evidence: "stored" as const }; }
  async beginAuthorization(params: { workspaceId: string; userId: string; appOrigin: string }) { const redirectUri = `${this.origin(params.appOrigin)}/api/knowledge/connections/${this.config.provider}/oauth/callback`; const db = await this.store.read(); const client = await this.oauthClient(db, redirectUri); const previous = this.connectionFor(db, params.workspaceId); const state = crypto.randomBytes(32).toString("base64url"); const verifier = crypto.randomBytes(48).toString("base64url"); await this.sessions.create({ workspaceId: params.workspaceId, userId: params.userId, connectorId: this.config.provider, protocol: "oauth_pkce", state, payload: { ...client, connectionId: previous?.id, previousStatus: previous?.status === "pending" ? undefined : previous?.status, redirectUri, verifier }, expiresAt: Date.now() + flowLifetimeMs }); await this.store.mutate(db2 => { const timestamp = new Date().toISOString(); let connection = this.connectionFor(db2, params.workspaceId); if (!connection) { connection = { id: uid("knc"), workspaceId: params.workspaceId, provider: this.config.provider, status: "pending", clientId: client.clientId, createdAt: timestamp, updatedAt: timestamp }; db2.knowledgeConnections.push(connection); } connection.status = "pending"; connection.clientId = client.clientId; connection.encryptedClientSecret = client.clientSecret ? this.protect(params.workspaceId, "client_secret", client.clientSecret) : undefined; connection.oauthTokenAuthMethod = client.tokenAuthMethod; connection.lastError = undefined; connection.updatedAt = timestamp; }); const url = new URL(this.config.authorizationUrl); url.search = new URLSearchParams({ response_type: "code", client_id: client.clientId, redirect_uri: redirectUri, code_challenge: challenge(verifier), code_challenge_method: "S256", state, resource: this.config.mcpUrl, scope: this.config.scope }).toString(); return { authorizationUrl: url.toString(), expiresIn: flowLifetimeMs / 1000 }; }
  async completeAuthorization(state: string, code: string) { const claimed = await this.sessions.claimState(this.config.provider, state); let flow: OAuthFlow; try { flow = this.oauthFlow(claimed.session, claimed.payload); } catch (error) { await this.sessions.finish(claimed.session.id); throw error; } let token: TokenResponse; try { token = await this.exchangeToken(flow, code); await this.sessions.markVerifying(claimed.session.id); await this.verifyAccessToken(token.access_token); } catch (error) { await this.sessions.finish(claimed.session.id); await this.restoreFlow(flow); throw error; } const timestamp = new Date().toISOString(); const connection = await this.store.mutate(db => { let target = this.connectionFor(db, flow.workspaceId); if (!target) { target = { id: uid("knc"), workspaceId: flow.workspaceId, provider: this.config.provider, status: "connected", clientId: flow.clientId, createdAt: timestamp, updatedAt: timestamp }; db.knowledgeConnections.push(target); } target.status = "connected"; target.clientId = token.client_id || flow.clientId; target.encryptedClientSecret = flow.clientSecret ? this.protect(flow.workspaceId, "client_secret", flow.clientSecret) : undefined; target.oauthTokenAuthMethod = flow.tokenAuthMethod; target.encryptedAccessToken = this.protect(flow.workspaceId, "access_token", token.access_token); target.encryptedRefreshToken = token.refresh_token ? this.protect(flow.workspaceId, "refresh_token", token.refresh_token) : undefined; target.credentialExpiresAt = token.expires_in ? new Date(Date.now() + token.expires_in * 1000).toISOString() : undefined; target.providerSpaceId = token.workspace_id; target.providerSpaceName = token.workspace_name; target.providerUserId = token.user_id; target.lastCheckedAt = timestamp; target.lastError = undefined; target.updatedAt = timestamp; db.auditLogs.push({ id: uid("aud"), workspaceId: flow.workspaceId, actorUserId: flow.userId, action: `knowledge.${this.config.provider}.connected`, targetType: "knowledge_connection", targetId: target.id, createdAt: timestamp }); return target; }); await this.sessions.finish(claimed.session.id); return connection; }
  async cancelAuthorization(state: string) { if (!state) return; const cancelled = await this.sessions.cancelState(this.config.provider, state); if (cancelled) await this.restoreFlow(this.oauthFlow(cancelled.session, cancelled.payload)); }
  async disconnect(workspaceId: string, userId: string) { const current = this.connectionFor(await this.store.read(), workspaceId); if (current?.encryptedAccessToken && this.config.revokeUrl) { const body = new URLSearchParams({ token: this.secret(current, "access_token", current.encryptedAccessToken), client_id: current.clientId }); await this.fetcher(assertAllowedConnectorUrl(this.config.revokeUrl, this.config.hosts), { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded" }, body, redirect: "error", signal: AbortSignal.timeout(3_000) }).catch(() => undefined); } await this.store.mutate(db => { const connection = this.connectionFor(db, workspaceId); if (!connection) return; connection.status = "revoked"; connection.encryptedAccessToken = undefined; connection.encryptedRefreshToken = undefined; connection.providerSpaceId = undefined; connection.providerSpaceName = undefined; connection.providerUserId = undefined; connection.updatedAt = new Date().toISOString(); db.auditLogs.push({ id: uid("aud"), workspaceId, actorUserId: userId, action: `knowledge.${this.config.provider}.disconnected`, targetType: "knowledge_connection", targetId: connection.id, createdAt: connection.updatedAt }); }); }
  async verify(workspaceId: string) { await this.withRefresh(workspaceId, connection => this.verifyClient(connection)); }
  async search(workspaceId: string, query: string, topK: number): Promise<KnowledgeChunk[]> { return this.withRefresh(workspaceId, connection => this.searchConnected(connection, query, topK)); }
  private async verifyAccessToken(accessToken: string) { const client = await deadline(this.createClient(accessToken), `${this.config.label} MCP 连接超时`); try { const list = await deadline(client.listTools(), `${this.config.label} MCP 工具查询超时`); if (!list.tools.some(tool => this.config.readOnlyTools.includes(tool.name))) throw new Error(`${this.config.label} MCP 没有可用的只读工具`); } finally { await closeClient(client, this.config.label); } }
  private async verifyClient(connection: KnowledgeConnection) { const client = await this.clientFor(connection); try { const list = await deadline(client.listTools(), `${this.config.label} MCP 工具查询超时`); const usable = list.tools.some(tool => this.config.readOnlyTools.includes(tool.name)); if (!usable) throw new Error(`${this.config.label} MCP 没有可用的只读工具`); } finally { await closeClient(client, this.config.label); } }
  private async searchConnected(connection: KnowledgeConnection, query: string, topK: number) { const client = await this.clientFor(connection); try { const listed = await deadline(client.listTools(), `${this.config.label} MCP 工具查询超时`); const available = new Set(listed.tools.map(tool => tool.name).filter(name => this.config.readOnlyTools.includes(name))); const searchTool = this.config.searchTools.find(name => available.has(name)); if (!searchTool) throw new Error(`${this.config.label} MCP 当前没有可用的只读搜索工具`); const result = await deadline(client.callTool({ name: searchTool, arguments: { query } }), `${this.config.label} MCP 搜索超时`); this.assertResult(result); const text = textContent(result); const found = candidates(jsonContent(text), this.config.sourceHosts).slice(0, Math.max(1, Math.min(10, topK))); if (!found.length) return text ? [{ provider: this.config.provider, title: `${this.config.label} 搜索结果`, content: text.slice(0, maxChunkChars) }] : []; const fetchTool = this.config.fetchTools.find(name => available.has(name)); const chunks: KnowledgeChunk[] = []; for (const item of found) { if (fetchTool && item.id) { try { const fetched = await deadline(client.callTool({ name: fetchTool, arguments: { id: item.id } }), `${this.config.label} MCP 读取超时`); this.assertResult(fetched); const body = textContent(fetched); const parsed = jsonContent(body); chunks.push({ id: item.id, provider: this.config.provider, title: stringValue(parsed, ["title", "name", "subject"]) || item.title || `${this.config.label} 内容`, sourceUrl: sourceUrl(stringValue(parsed, ["url", "href", "link"]) || item.url, this.config.sourceHosts), content: (stringValue(parsed, ["text", "content", "markdown"]) || body || item.excerpt || item.title || "").slice(0, maxChunkChars) }); continue; } catch (error) { if (this.isAuthorizationError(error)) throw error; } } chunks.push({ id: item.id, provider: this.config.provider, title: item.title || `${this.config.label} 内容`, sourceUrl: item.url, content: (item.excerpt || item.title || "").slice(0, maxChunkChars) }); } return chunks.filter(item => item.content); } finally { await closeClient(client, this.config.label); } }
  private assertResult(result: unknown) { if (result && typeof result === "object" && (result as { isError?: unknown }).isError === true) throw new Error(`${this.config.label} MCP 读取失败`); }
  private isAuthorizationError(error: unknown) { const value = error instanceof Error ? `${error.name} ${error.message}` : String(error); return /unauthori[sz]ed|invalid[_ -]?token|expired[_ -]?token|\b401\b/i.test(value); }
  private async withRefresh<T>(workspaceId: string, operation: (connection: KnowledgeConnection) => Promise<T>) { let connection = await this.connected(workspaceId); try { return await operation(connection); } catch (error) { if (!connection.encryptedRefreshToken || !this.isAuthorizationError(error)) throw error; await this.refreshAccessToken(connection); connection = await this.connected(workspaceId); return operation(connection); } }
  private async connected(workspaceId: string) { let db = await this.store.read(); let connection = this.connectionFor(db, workspaceId); if (!connection || connection.status === "revoked" || !connection.encryptedAccessToken) throw new Error(`请先连接 ${this.config.label}`); if (connection.credentialExpiresAt && Date.parse(connection.credentialExpiresAt) <= Date.now() + 60_000) { await this.refreshAccessToken(connection); db = await this.store.read(); connection = this.connectionFor(db, workspaceId); } if (!connection?.encryptedAccessToken) throw new Error(`${this.config.label} 授权资料不完整，请重新连接`); return connection; }
  private async clientFor(connection: KnowledgeConnection) { return deadline(this.createClient(this.secret(connection, "access_token", connection.encryptedAccessToken!)), `${this.config.label} MCP 连接超时`); }
  private async refreshAccessToken(connection: KnowledgeConnection) { const existing = this.refreshes.get(connection.workspaceId); if (existing) return existing; const refresh = (async () => { if (!connection.encryptedRefreshToken) throw new Error(`${this.config.label} 授权已过期，请重新连接`); const body = new URLSearchParams({ grant_type: "refresh_token", refresh_token: this.secret(connection, "refresh_token", connection.encryptedRefreshToken), client_id: connection.clientId }); if (connection.encryptedClientSecret && connection.oauthTokenAuthMethod === "client_secret_post") body.append("client_secret", this.secret(connection, "client_secret", connection.encryptedClientSecret)); const response = await this.fetcher(assertAllowedConnectorUrl(this.config.tokenUrl, this.config.hosts), { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", Accept: "application/json" }, body, redirect: "error" }); if (!response.ok) throw new Error(`${this.config.label} 授权已过期，请重新连接`); const token = tokenResponse(await readBoundedJson<unknown>(response, 256 * 1024), this.config.label); await this.store.mutate(db => { const target = this.connectionFor(db, connection.workspaceId); if (!target || target.id !== connection.id || target.status === "revoked") throw new Error(`${this.config.label} 连接已被撤销`); target.encryptedAccessToken = this.protect(target.workspaceId, "access_token", token.access_token); if (token.refresh_token) target.encryptedRefreshToken = this.protect(target.workspaceId, "refresh_token", token.refresh_token); target.credentialExpiresAt = token.expires_in ? new Date(Date.now() + token.expires_in * 1000).toISOString() : undefined; target.status = "connected"; target.lastError = undefined; target.updatedAt = new Date().toISOString(); }); return token.access_token; })().finally(() => this.refreshes.delete(connection.workspaceId)); this.refreshes.set(connection.workspaceId, refresh); return refresh; }
  private async oauthClient(db: Database, redirectUri: string): Promise<OAuthClient> { const prefix = this.config.envPrefix; const configuredId = process.env[`${prefix}_CLIENT_ID`]?.trim(); if (configuredId) { const secret = process.env[`${prefix}_CLIENT_SECRET`]?.trim() || undefined; return { clientId: configuredId, clientSecret: secret, tokenAuthMethod: secret ? "client_secret_post" : "none" }; } const stored = db.knowledgeConnections.find(item => item.provider === this.config.provider && item.clientId && item.oauthTokenAuthMethod); if (stored) return { clientId: stored.clientId, clientSecret: stored.encryptedClientSecret ? this.secret(stored, "client_secret", stored.encryptedClientSecret) : undefined, tokenAuthMethod: stored.oauthTokenAuthMethod! }; const response = await this.fetcher(assertAllowedConnectorUrl(this.config.registrationUrl, this.config.hosts), { method: "POST", redirect: "error", headers: { "Content-Type": "application/json", Accept: "application/json" }, body: JSON.stringify({ client_name: "ONE", client_uri: this.origin(redirectUri), redirect_uris: [redirectUri], grant_types: ["authorization_code", "refresh_token"], response_types: ["code"], token_endpoint_auth_method: "none" }) }); if (!response.ok) throw new Error(`暂时无法初始化 ${this.config.label} 授权，请稍后重试`); const registered = await readBoundedJson<Record<string, unknown>>(response, 256 * 1024); return { clientId: requiredString(registered.client_id, "OAuth Client ID", 2_000), tokenAuthMethod: "none" }; }
  private async exchangeToken(flow: OAuthFlow, code: string) { const body = new URLSearchParams({ grant_type: "authorization_code", code, redirect_uri: flow.redirectUri, client_id: flow.clientId, code_verifier: flow.verifier }); if (flow.clientSecret && flow.tokenAuthMethod === "client_secret_post") body.append("client_secret", flow.clientSecret); const response = await this.fetcher(assertAllowedConnectorUrl(this.config.tokenUrl, this.config.hosts), { method: "POST", headers: { "Content-Type": "application/x-www-form-urlencoded", Accept: "application/json", "User-Agent": "ONE-MCP-Client/0.1" }, body, redirect: "error" }); if (!response.ok) throw new Error(`${this.config.label} 授权确认失败，请返回 ONE 重试`); return tokenResponse(await readBoundedJson<unknown>(response, 256 * 1024), this.config.label); }
  private oauthFlow(session: ConnectorAuthorizationSession, payload: Record<string, unknown>): OAuthFlow { const required = (key: string) => { const value = payload[key]; if (typeof value !== "string" || !value) throw new Error(`${this.config.label} 授权资料格式无效`); return value; }; const method = payload.tokenAuthMethod; if (method !== "none" && method !== "client_secret_post") throw new Error(`${this.config.label} 授权客户端认证方式无效`); return { workspaceId: session.workspaceId, userId: session.userId, clientId: required("clientId"), clientSecret: typeof payload.clientSecret === "string" ? payload.clientSecret : undefined, tokenAuthMethod: method, connectionId: typeof payload.connectionId === "string" ? payload.connectionId : undefined, previousStatus: payload.previousStatus as KnowledgeConnection["status"] | undefined, redirectUri: required("redirectUri"), verifier: required("verifier") }; }
  private async restoreFlow(flow: OAuthFlow) { await this.store.mutate(db => { const connection = this.connectionFor(db, flow.workspaceId); if (!connection) return; if (flow.connectionId && connection.id === flow.connectionId) connection.status = flow.previousStatus || "revoked"; else if (!flow.connectionId && connection.status === "pending") connection.status = "revoked"; connection.updatedAt = new Date().toISOString(); }); }
}
