import type { Store } from "../db.js";
import { AuthorizationSessions } from "../connectors/authorizationSessions.js";
import { uid } from "../security.js";
import type { ConnectorAuthorizationSession, Database, KnowledgeConnection } from "../types.js";
import { decryptCredential, encryptCredential, knowledgeCredentialContext } from "./credentialCipher.js";
import type { KnowledgeChunk } from "./provider.js";
import { Client } from "evernote";

const provider = "yinxiang" as const;
const flowLifetimeMs = 10 * 60 * 1000;
const maxChunkChars = 24_000;

type YinxiangClient = InstanceType<typeof Client>;
type OAuthFlow = { workspaceId: string; userId: string; connectionId?: string; previousStatus?: KnowledgeConnection["status"]; requestToken: string; requestTokenSecret: string };
export type YinxiangServiceOptions = { createClient?: (options: ConstructorParameters<typeof Client>[0]) => YinxiangClient };

function required(value: unknown, message: string, max = 65_536) { if (typeof value !== "string" || !value || value.length > max) throw new Error(message); return value; }
function stripEnml(value: string) { return value.replace(/<en-media\b[^>]*\/?>/gi, " [附件] ").replace(/<br\s*\/?>/gi, "\n").replace(/<\/div>|<\/p>|<\/li>/gi, "\n").replace(/<[^>]+>/g, " ").replace(/&nbsp;/gi, " ").replace(/&amp;/gi, "&").replace(/&lt;/gi, "<").replace(/&gt;/gi, ">").replace(/[ \t]+/g, " ").replace(/ *\n */g, "\n").replace(/\n{3,}/g, "\n\n").trim(); }

export class YinxiangService {
  private readonly sessions: AuthorizationSessions;
  private readonly createClient: (options: ConstructorParameters<typeof Client>[0]) => YinxiangClient;
  constructor(private store: Store, options: YinxiangServiceOptions = {}) { this.sessions = new AuthorizationSessions(store); this.createClient = options.createClient || (value => new Client(value)); }
  configured() { return Boolean(process.env.YINXIANG_CONSUMER_KEY?.trim() && process.env.YINXIANG_CONSUMER_SECRET?.trim()); }
  private appClient(token?: string) { const consumerKey = process.env.YINXIANG_CONSUMER_KEY?.trim(); const consumerSecret = process.env.YINXIANG_CONSUMER_SECRET?.trim(); if (!consumerKey || !consumerSecret) throw new Error("印象笔记连接暂未开通，请联系管理员"); return this.createClient({ consumerKey, consumerSecret, sandbox: false, china: true, token }); }
  private connectionFor(db: Database, workspaceId: string) { return db.knowledgeConnections.find(item => item.workspaceId === workspaceId && item.provider === provider); }
  private protect(workspaceId: string, token: string) { return encryptCredential(token, knowledgeCredentialContext(workspaceId, provider, "access_token")); }
  private token(connection: KnowledgeConnection) { return decryptCredential(connection.encryptedAccessToken!, knowledgeCredentialContext(connection.workspaceId, provider, "access_token")); }
  localStatus(db: Database, workspaceId: string) { const connection = this.connectionFor(db, workspaceId); if (!connection || connection.status === "revoked") return { state: "not_connected" as const, code: "AUTHORIZATION_REQUIRED", message: "请连接印象笔记", evidence: "stored" as const }; if (connection.status === "pending") return { state: "pending" as const, code: "AUTHORIZATION_PENDING", message: "等待完成印象笔记授权", evidence: "stored" as const }; if (connection.status === "error") return { state: "error" as const, code: "CONNECTION_ERROR", message: "印象笔记连接需要检查", evidence: "stored" as const }; if (!connection.encryptedAccessToken) return { state: "not_connected" as const, code: "CREDENTIAL_UNAVAILABLE", message: "印象笔记授权资料不完整，请重新连接", evidence: "stored" as const }; return { state: "configured" as const, code: "CREDENTIAL_STORED", message: "已保存印象笔记授权", evidence: "stored" as const }; }
  async beginAuthorization(params: { workspaceId: string; userId: string; appOrigin: string }) { const origin = new URL(params.appOrigin).origin; if (process.env.NODE_ENV === "production" && !origin.startsWith("https://")) throw new Error("生产环境的 APP_ORIGIN 必须使用 HTTPS"); const callback = `${origin}/api/knowledge/connections/yinxiang/oauth/callback`; const client = this.appClient(); const request = await new Promise<{ token: string; secret: string }>((resolve, reject) => client.getRequestToken(callback, (error, token, secret) => error ? reject(new Error("暂时无法初始化印象笔记授权，请稍后重试")) : resolve({ token: required(token, "印象笔记临时授权无效"), secret: required(secret, "印象笔记临时授权无效") }))); const db = await this.store.read(); const previous = this.connectionFor(db, params.workspaceId); await this.sessions.create({ workspaceId: params.workspaceId, userId: params.userId, connectorId: provider, protocol: "oauth1", state: request.token, payload: { clientId: process.env.YINXIANG_CONSUMER_KEY!.trim(), requestToken: request.token, requestTokenSecret: request.secret, connectionId: previous?.id, previousStatus: previous?.status === "pending" ? undefined : previous?.status }, expiresAt: Date.now() + flowLifetimeMs }); await this.store.mutate(db2 => { const timestamp = new Date().toISOString(); const connection = this.connectionFor(db2, params.workspaceId)!; if (connection.status !== "connected") connection.status = "pending"; connection.lastError = undefined; connection.updatedAt = timestamp; }); const authorizationUrl = client.getAuthorizeUrl(request.token); const url = new URL(authorizationUrl); if (url.protocol !== "https:" || url.hostname !== "app.yinxiang.com" || url.pathname !== "/OAuth.action") throw new Error("印象笔记返回了无效的授权地址"); return { authorizationUrl: url.toString(), expiresIn: flowLifetimeMs / 1000 }; }
  async completeAuthorization(state: string, verifier: string) { const claimed = await this.sessions.claimState(provider, state); let flow: OAuthFlow; try { flow = this.flow(claimed.session, claimed.payload); } catch (error) { await this.sessions.finish(claimed.session.id); throw error; } try { const client = this.appClient(); const access = await new Promise<{ token: string; results: Record<string, unknown> }>((resolve, reject) => client.getAccessToken(flow.requestToken, flow.requestTokenSecret, verifier, (error, token, _secret, results) => error ? reject(new Error("印象笔记授权确认失败，请返回 ONE 重试")) : resolve({ token: required(token, "印象笔记访问令牌无效"), results: results || {} }))); await this.sessions.markVerifying(claimed.session.id); const user = await this.verifyToken(access.token); const timestamp = new Date().toISOString(); const connection = await this.store.mutate(db => { let target = this.connectionFor(db, flow.workspaceId); if (!target) { target = { id: uid("knc"), workspaceId: flow.workspaceId, provider, status: "connected", clientId: process.env.YINXIANG_CONSUMER_KEY!.trim(), createdAt: timestamp, updatedAt: timestamp }; db.knowledgeConnections.push(target); } target.status = "connected"; target.encryptedAccessToken = this.protect(flow.workspaceId, access.token); target.providerSpaceName = user.name || user.username || "印象笔记"; target.providerUserId = user.id === undefined ? undefined : String(user.id); target.credentialExpiresAt = typeof access.results.edam_expires === "string" && /^\d+$/.test(access.results.edam_expires) ? new Date(Number(access.results.edam_expires)).toISOString() : undefined; target.lastCheckedAt = timestamp; target.lastError = undefined; target.updatedAt = timestamp; db.auditLogs.push({ id: uid("aud"), workspaceId: flow.workspaceId, actorUserId: flow.userId, action: "knowledge.yinxiang.connected", targetType: "knowledge_connection", targetId: target.id, createdAt: timestamp }); return target; }); await this.sessions.finish(claimed.session.id); return connection; } catch (error) { await this.sessions.finish(claimed.session.id); await this.restore(flow); throw error; } }
  async cancelAuthorization(state: string) { if (!state) return; const cancelled = await this.sessions.cancelState(provider, state); if (cancelled) await this.restore(this.flow(cancelled.session, cancelled.payload)); }
  async disconnect(workspaceId: string, userId: string) { await this.store.mutate(db => { const connection = this.connectionFor(db, workspaceId); if (!connection) return; connection.status = "revoked"; connection.encryptedAccessToken = undefined; connection.providerSpaceName = undefined; connection.providerUserId = undefined; connection.updatedAt = new Date().toISOString(); db.auditLogs.push({ id: uid("aud"), workspaceId, actorUserId: userId, action: "knowledge.yinxiang.disconnected", targetType: "knowledge_connection", targetId: connection.id, createdAt: connection.updatedAt }); }); }
  async verify(workspaceId: string) { await this.verifyToken(this.token(await this.connected(workspaceId))); }
  private async verifyToken(token: string) { return this.appClient(token).getUserStore().getUser(); }
  async search(workspaceId: string, query: string, topK: number): Promise<KnowledgeChunk[]> { const connection = await this.connected(workspaceId); const client = this.appClient(this.token(connection)); const urls = await client.getUserStore().getUserUrls(); const noteStoreUrl = required(urls.noteStoreUrl, "印象笔记返回了无效的读取地址", 2_000); const endpoint = new URL(noteStoreUrl); if (endpoint.protocol !== "https:" || endpoint.hostname !== "app.yinxiang.com" || endpoint.port) throw new Error("印象笔记返回了无效的读取地址"); const notes = client.getNoteStore(endpoint.toString()); const count = Math.max(1, Math.min(10, Math.floor(topK))); const result = await notes.findNotesMetadata({ words: query, inactive: false, includeAllReadableNotebooks: true }, 0, count, { includeTitle: true }); const chunks: KnowledgeChunk[] = []; for (const metadata of result.notes || []) { if (!metadata.guid) continue; try { const note = await notes.getNote(metadata.guid, true, false, false, false); const content = stripEnml(note.content || ""); if (content) chunks.push({ id: metadata.guid, provider, title: note.title || metadata.title || "印象笔记", sourceUrl: "https://app.yinxiang.com/Home.action", content: content.slice(0, maxChunkChars) }); } catch { /* One unreadable note must not discard other matches. */ } } return chunks; }
  private async connected(workspaceId: string) { const connection = this.connectionFor(await this.store.read(), workspaceId); if (!connection || connection.status === "revoked" || !connection.encryptedAccessToken) throw new Error("请先连接印象笔记"); return connection; }
  private flow(session: ConnectorAuthorizationSession, payload: Record<string, unknown>): OAuthFlow { return { workspaceId: session.workspaceId, userId: session.userId, requestToken: required(payload.requestToken, "印象笔记授权资料格式无效", 2_000), requestTokenSecret: required(payload.requestTokenSecret, "印象笔记授权资料格式无效", 2_000), connectionId: typeof payload.connectionId === "string" ? payload.connectionId : undefined, previousStatus: payload.previousStatus as KnowledgeConnection["status"] | undefined }; }
  private async restore(flow: OAuthFlow) { await this.store.mutate(db => { const connection = this.connectionFor(db, flow.workspaceId); if (!connection) return; if (flow.connectionId && connection.id === flow.connectionId) connection.status = flow.previousStatus || "revoked"; else if (!flow.connectionId && connection.status === "pending") connection.status = "revoked"; connection.updatedAt = new Date().toISOString(); }); }
}
