import { useEffect, useState } from "react";
import type { api as Api } from "./oneApi";
import type { companySummary } from "../server/companyService";
import "./company-panel.css";

type Detail = ReturnType<typeof companySummary>;
type CompanyRow = {id:string;name:string;status:string;agreementRef:string;members:number};
type Feature = {id:string;name:string;revision:number;version:number;enabled:boolean};
export function CompanyPanel({api,platform=false}:{api:typeof Api;platform?:boolean}) {
  const [items,setItems]=useState<CompanyRow[]>([]),[selected,setSelected]=useState(''),[detail,setDetail]=useState<Detail>(),[features,setFeatures]=useState<Feature[]>([]);
  const [name,setName]=useState(''),[agreement,setAgreement]=useState(''),[owner,setOwner]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
  const [username,setUsername]=useState(''),[role,setRole]=useState('member'),[employee,setEmployee]=useState(''),[serial,setSerial]=useState('');
  const [bankReference,setBankReference]=useState(''),[amount,setAmount]=useState(''),[power,setPower]=useState(''),[confirmed,setConfirmed]=useState(false);
  const base=platform?`/api/admin/companies/${encodeURIComponent(selected)}`:'/api/company';
  async function loadList(){if(platform){const result=await api<{items:CompanyRow[]}>('/api/admin/companies');setItems(result.items);}}
  async function loadDetail(){if(platform&&!selected){setDetail(undefined);return;}setDetail(await api<Detail>(base));if(platform)setFeatures((await api<{items:Feature[]}>(base+'/features')).items);}
  useEffect(()=>{let live=true;if(platform)void api<{items:CompanyRow[]}>('/api/admin/companies').then(r=>{if(live)setItems(r.items);}).catch(e=>{if(live)setNotice(e.message);});return()=>{live=false;};},[api,platform]);
  useEffect(()=>{let live=true;setDetail(undefined);setEmployee('');if(platform&&!selected)return;void api<Detail>(base).then(r=>{if(live)setDetail(r);}).catch(e=>{if(live)setNotice(e.message);});if(platform)void api<{items:Feature[]}>(base+'/features').then(r=>{if(live)setFeatures(r.items);}).catch(e=>{if(live)setNotice(e.message);});return()=>{live=false;};},[api,base,platform,selected]);
  async function run(work:()=>Promise<unknown>){if(busy)return;setBusy(true);setNotice('');try{await work();await loadList();await loadDetail();setNotice('已保存');}catch(e){setNotice(e instanceof Error?e.message:'未能完成，请刷新重试');}finally{setBusy(false);}}
  const member=detail?.members.find(m=>m.userId===employee);
  async function patchMember(userId:string,patch:Record<string,unknown>){await api(base+`/members/${encodeURIComponent(userId)}`,{method:'PATCH',body:JSON.stringify({revision:detail?.company.revision,...patch})});}
  function download(value:unknown,filename:string){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=filename;a.click();URL.revokeObjectURL(url);}
  return <section className="company-panel" aria-label={platform?'企业管理':'公司管理'}>
    <header className="section-toolbar"><h2>{platform?'企业管理':detail?.company.name??'公司管理'}</h2><button type="button" disabled={busy} onClick={()=>void run(async()=>{})}>刷新</button></header>
    <p>通过 ONE Key 进入公司；管理员管理本公司成员与授权，员工的私人对话和附件不在此展示。</p>
    {notice?<p role="status" className="notice">{notice}</p>:null}
    {platform?<><details><summary>开通公司</summary><form onSubmit={e=>{e.preventDefault();void run(async()=>{const r=await api<{company:{id:string}}>('/api/admin/companies',{method:'POST',body:JSON.stringify({name,agreementRef:agreement,ownerUsername:owner})});setSelected(r.company.id);setName('');setOwner('');setAgreement('');});}}><label>公司名称<input required maxLength={120} value={name} onChange={e=>setName(e.target.value)}/></label><label>协议编号<input required maxLength={120} value={agreement} onChange={e=>setAgreement(e.target.value)}/></label><label>管理员账号标识<input required maxLength={64} value={owner} onChange={e=>setOwner(e.target.value)} placeholder="用于配发 Key，无需密码登录"/></label><button className="primary" disabled={busy}>创建公司与管理员</button></form></details><label>选择公司<select disabled={busy} value={selected} onChange={e=>{setSelected(e.target.value);setNotice('');}}><option value="">请选择</option>{items.map(c=><option key={c.id} value={c.id}>{c.name} · {c.status==='active'?'正常':'停用'}</option>)}</select></label></>:null}
    {detail?<><div className="company-overview"><span>协议：{detail.company.company?.agreementRef}</span><span>公司电力：{(detail.billing.balanceMicros/1e6).toFixed(3)}</span><span>预留：{(detail.billing.reservedMicros/1e6).toFixed(3)}</span><span>已用：{(detail.billing.chargedMicros/1e6).toFixed(3)}</span></div>
      {platform?<button disabled={busy} type="button" onClick={()=>{if(confirm(`${detail.company.status==='active'?'停用':'恢复'} ${detail.company.name}？`))void run(()=>api(base,{method:'PATCH',body:JSON.stringify({revision:detail.company.revision,status:detail.company.status==='active'?'suspended':'active'})}));}}>{detail.company.status==='active'?'停用公司':'恢复公司'}</button>:null}
      <h3>成员与权限</h3><form onSubmit={e=>{e.preventDefault();void run(async()=>{await api(base+'/members',{method:'POST',body:JSON.stringify({username,role})});setUsername('');});}}><label>新成员账号标识<input required maxLength={64} value={username} onChange={e=>setUsername(e.target.value)}/></label><label>角色<select value={role} onChange={e=>setRole(e.target.value)}><option value="member">员工</option><option value="owner">公司管理员</option></select></label><button disabled={busy}>添加成员</button></form>
      <label>选择成员<select value={employee} onChange={e=>setEmployee(e.target.value)}><option value="">请选择</option>{detail.members.map(m=><option key={m.userId} value={m.userId}>{m.username} · {m.role==='owner'?'管理员':'员工'}{m.status==='disabled'?' · 已停用':''}</option>)}</select></label>
      {member?<MemberPermissions key={`${member.userId}:${detail.company.revision}`} member={member} detail={detail} busy={busy} save={patch=>run(()=>patchMember(member.userId,patch))}/>:null}
      <h3>ONE Key</h3><form onSubmit={e=>{e.preventDefault();void run(async()=>{const r=await api<{deviceConfig:unknown}>(base+'/keys',{method:'POST',body:JSON.stringify({userId:employee,serialNumber:serial})});download(r.deviceConfig,`${serial}.one-key.json`);setSerial('');});}}><p>为上方选定的有效成员配发 Key，下载的凭证交给现有灌装流程。</p><label>序列号<input required pattern="[-A-Za-z0-9_]{3,80}" value={serial} onChange={e=>setSerial(e.target.value)}/></label><button disabled={busy||!member||member.status!=='active'}>生成 Key 凭证</button></form>
      <ul>{detail.devices.map(d=><li key={d.id}>{d.serialNumber} · {detail.members.find(m=>m.userId===d.userId)?.username} · {d.status==='active'?'有效':'已挂失'} {d.status==='active'?<button type="button" disabled={busy} onClick={()=>{if(confirm(`挂失 ${d.serialNumber}？`))void run(()=>api(base+`/keys/${encodeURIComponent(d.id)}/revoke`,{method:'POST'}));}}>挂失</button>:null}</li>)}</ul>
      <h3>知识与功能</h3><p>知识连接由公司管理员在“设置 → 知识来源”授权。员工只可使用明确分配的来源与功能。</p><ul>{detail.knowledge.map(k=><li key={k.id}>{k.name} · {k.status}</li>)}</ul>
      {platform?<div>{features.map(f=><label className="company-check" key={f.id}><input type="checkbox" checked={f.enabled} disabled={busy} onChange={e=>void run(()=>api(base+`/features/${encodeURIComponent(f.id)}`,{method:'POST',body:JSON.stringify({revision:f.revision,enabled:e.target.checked,version:f.version})}))}/>{f.name} · 可交付 v{f.version}</label>)}</div>:<ul>{detail.features.map(f=><li key={f.id}>{f.name} · v{f.version}</li>)}</ul>}
      <h3>对公款项</h3><p>按照协议公对公打款，由平台核实到账后记录金额和协议电力。此处不发起转账。</p>
      {platform?<form onSubmit={e=>{e.preventDefault();void run(async()=>{await api(base+'/payments',{method:'POST',body:JSON.stringify({bankReference,amountFen:Math.round(Number(amount)*100),amountMicros:Math.round(Number(power)*1e6),confirmed})});setConfirmed(false);setBankReference('');setAmount('');setPower('');});}}><label>银行流水编号<input required maxLength={160} value={bankReference} onChange={e=>setBankReference(e.target.value)}/></label><label>到账金额（元）<input required type="number" min="0.01" step="0.01" value={amount} onChange={e=>setAmount(e.target.value)}/></label><label>协议入账电力<input required type="number" min="0.000001" step="0.000001" value={power} onChange={e=>setPower(e.target.value)}/></label><label className="company-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>已核实实际到账及协议额度</label><button disabled={busy||!confirmed}>记录到账并入账</button></form>:null}
      <ul>{detail.payments.map(p=><li key={p.id}>{p.bankReference} · ¥{p.amountCny.toFixed(2)} · {p.requestedMicros/1e6} 电力</li>)}</ul>
    </>:null}
  </section>;
}
function MemberPermissions({member,detail,busy,save}:{member:Detail['members'][number];detail:Detail;busy:boolean;save:(patch:Record<string,unknown>)=>Promise<void>}) {
  const [knowledge,setKnowledge]=useState(member.permissions.knowledgeConnectionIds),[features,setFeatures]=useState(member.permissions.featureIds),[limit,setLimit]=useState(member.permissions.powerLimitMicros===undefined?'':String(member.permissions.powerLimitMicros/1e6)),[role,setRole]=useState(member.role);
  const toggle=(ids:string[],id:string)=>ids.includes(id)?ids.filter(i=>i!==id):[...ids,id];
  return <form onSubmit={e=>{e.preventDefault();void save({role,permissions:{knowledgeConnectionIds:knowledge.filter(id=>detail.knowledge.some(k=>k.id===id&&k.status!=='revoked')),featureIds:features.filter(id=>detail.features.some(f=>f.id===id)),...(limit!==''?{powerLimitMicros:Math.round(Number(limit)*1e6)}:{})}});}}><label>角色<select value={role} onChange={e=>setRole(e.target.value as typeof role)}><option value="member">员工</option><option value="owner">公司管理员</option></select></label><p>公司管理员可使用已交付资源；以下知识和功能勾选用于员工授权。</p><fieldset><legend>可用知识</legend>{detail.knowledge.filter(k=>k.status!=='revoked').map(k=><label className="company-check" key={k.id}><input type="checkbox" checked={knowledge.includes(k.id)} onChange={()=>setKnowledge(toggle(knowledge,k.id))}/>{k.name}</label>)}</fieldset><fieldset><legend>可用功能</legend>{detail.features.map(f=><label className="company-check" key={f.id}><input type="checkbox" checked={features.includes(f.id)} onChange={()=>setFeatures(toggle(features,f.id))}/>{f.name}</label>)}</fieldset><label>累计电力额度<input type="number" min="0" step="0.000001" value={limit} onChange={e=>setLimit(e.target.value)} placeholder="留空不设员工上限；0 表示暂停用量"/></label><button disabled={busy}>保存权限</button><button type="button" disabled={busy} onClick={()=>{if(confirm(`${member.status==='active'?'停用':'恢复'}此成员？停用会永久挂失其现有 Key，恢复后需重新配发。`))void save({status:member.status==='active'?'disabled':'active'});}}>{member.status==='active'?'停用成员':'恢复成员'}</button></form>;
}
