import { useEffect, useState } from 'react';
import type { api as Api } from './oneApi';
import type { McpDefinition } from '../server/connectors/featureMcp';
import type { FeatureToolChoice } from '../server/featureTools';
import { SearchPicker } from './SettingsControls';
type Auth='bearer'|'api_key';
export function MyToolCredentials({api}:{api:typeof Api}){
  const [items,setItems]=useState<{endpoint:string;auth:Auth}[]>([]),[page,setPage]=useState(1),[error,setError]=useState('');
  async function load(){try{const r=await api<{items:typeof items}>('/api/feature-credentials');setItems(r.items);setPage(1);setError('');}catch{setError('无法读取凭证列表');}}
  return <details onToggle={e=>{if(e.currentTarget.open)void load();}}><summary>我的外部工具凭证</summary><p className="hint">即使功能已经下架，也可以在这里撤销凭证。撤销或更换会停止使用旧凭证的后续调用。</p><button type="button" onClick={()=>void load()}>刷新列表</button>{items.slice((page-1)*5,page*5).map(c=><ToolCredentialEditor key={`${c.endpoint}:${c.auth}`} api={api} {...c}/>)}{!items.length?<p>暂无凭证</p>:null}<button type="button" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><span> {page} / {Math.max(1,Math.ceil(items.length/5))} </span><button type="button" disabled={page*5>=items.length} onClick={()=>setPage(page+1)}>下一页</button>{error?<p role="alert">{error}</p>:null}</details>;
}
export function ToolCredentialEditor({api,endpoint,auth}:{api:typeof Api;endpoint:string;auth:Auth}){
  const [secret,setSecret]=useState(''),[configured,setConfigured]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{let active=true;setConfigured(false);setSecret('');void api<{items:{endpoint:string;auth:string}[]}>('/api/feature-credentials').then(r=>{if(active)setConfigured(r.items.some(c=>c.endpoint===endpoint&&c.auth===auth));}).catch(()=>{if(active)setMessage('无法读取凭证状态');});return()=>{active=false;};},[api,endpoint,auth]);
  async function save(remove=false){setBusy(true);setMessage('');try{await api('/api/feature-credentials',{method:remove?'DELETE':'POST',body:JSON.stringify({endpoint,auth,...(!remove?{secret}:{})})});setSecret('');setConfigured(!remove);setMessage(remove?'已撤销':'已加密保存，仅供本人使用');}catch(e){setMessage(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
  return <details><summary>我的接口凭证 · {configured?'已配置':'未配置'}</summary><p className="hint" style={{overflowWrap:'anywhere'}}>{endpoint} · {auth==='bearer'?'Bearer':'X-API-Key'}。不会分享给其他用户，也不会发送给模型。</p><label>凭证<input type="password" autoComplete="new-password" value={secret} onChange={e=>setSecret(e.target.value)} maxLength={8000}/></label><button type="button" disabled={busy||secret.length<8} onClick={()=>void save()}>保存本人凭证</button>{configured?<button type="button" disabled={busy} onClick={()=>void save(true)}>撤销</button>:null}{message?<p role="status">{message}</p>:null}</details>;
}
export function ToolAuthPicker({value,onChange}:{value?:Auth;onChange:(v:Auth|undefined)=>void}){return <div className="settings-tabs">{([['','无需凭证'],['bearer','Bearer'],['api_key','API Key']] as const).map(([v,label])=><button type="button" key={v} aria-pressed={(value??'')===v} onClick={()=>onChange(v||undefined)}>{label}</button>)}</div>;}
export function McpToolPicker({api,endpoints,tools,onAdd}:{api:typeof Api;endpoints:string[];tools:FeatureToolChoice[];onAdd:(tool:FeatureToolChoice)=>void}){
  const [endpoint,setEndpoint]=useState(''),[auth,setAuth]=useState<Auth>(),[found,setFound]=useState<McpDefinition[]>([]),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[query,setQuery]=useState(''),[page,setPage]=useState(1),[reviewed,setReviewed]=useState<string[]>([]);
  const reset=()=>{setFound([]);setReviewed([]);setMessage('');setPage(1);};
  const filtered=found.filter(t=>`${t.name} ${t.description??''}`.toLowerCase().includes(query.toLowerCase()));
  async function discover(){setBusy(true);reset();try{const r=await api<{tools:McpDefinition[];unsupported:number}>('/api/admin/official-features/mcp-discover',{method:'POST',body:JSON.stringify({endpoint,auth})});setFound(r.tools);setMessage(`发现 ${r.tools.length} 个支持的工具；${r.unsupported} 个不符合当前只读接口规则。`);}catch(e){setMessage(e instanceof Error?e.message:'发现失败');}finally{setBusy(false);}}
  return <details><summary>添加远程 MCP 能力</summary><p className="hint">先发现工具，再人工核对只读行为。当前支持远程 HTTP、简单参数与文本结果；不支持本机 MCP、OAuth 和写入操作。</p><SearchPicker label="已审核的服务地址" value={endpoint} options={endpoints.map(e=>({value:e,label:e}))} onChange={v=>{setEndpoint(v);reset();}}/><ToolAuthPicker value={auth} onChange={v=>{setAuth(v);reset();}}/>{endpoint&&auth?<ToolCredentialEditor key={`${endpoint}:${auth}`} api={api} endpoint={endpoint} auth={auth}/>:null}<button type="button" disabled={busy||!endpoint} onClick={()=>void discover()}>{busy?'发现中…':'发现工具（不执行）'}</button>{message?<p role="status">{message}</p>:null}{found.length?<><label>搜索工具<input value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/></label>{filtered.slice((page-1)*5,page*5).map(tool=><details key={tool.name}><summary>{tool.name}</summary><p>{tool.description}</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{JSON.stringify(tool.inputSchema,null,2)}</pre><label><input type="checkbox" checked={reviewed.includes(tool.name)} onChange={e=>setReviewed(e.target.checked?[...reviewed,tool.name]:reviewed.filter(n=>n!==tool.name))}/>我已核对该工具仅做读取，且适合本智能体</label><button type="button" disabled={tools.length>=6||!reviewed.includes(tool.name)} onClick={()=>{const id=tool.name.replaceAll('-','_');if(tools.some(t=>t.id===id)){setMessage('工具标识重复，请先移除同名工具');return;}onAdd({id,description:(tool.description||'请填写调用条件与参数规则').slice(0,2000),auth,mcp:{endpoint,tool,reviewedReadOnly:true}});setMessage(`已添加 ${tool.name}，保存智能体后生效`);}}>添加能力</button></details>)}<button type="button" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><span> {page} / {Math.max(1,Math.ceil(filtered.length/5))} </span><button type="button" disabled={page*5>=filtered.length} onClick={()=>setPage(page+1)}>下一页</button></>:null}</details>;
}
