import type {FeatureExperience,FeatureInput} from '../server/featureExperience';
import {FeatureOptions,featureDefaults} from './FeatureOptions';
export function FeatureExperienceEditor({value,onChange}:{value?:FeatureExperience;onChange:(v:FeatureExperience|undefined)=>void}){
 const current=value??{inputs:[],actions:[{id:'start',label:'开始任务',instruction:'完成用户任务'}]};
 const updateInput=(id:string,patch:Partial<FeatureInput>)=>onChange({...current,inputs:current.inputs.map(f=>f.id===id?{...f,...patch}:f)});
 const identifier=(prefix:string,existing:string[])=>{let n=1;while(existing.includes(prefix+n))n++;return prefix+n;};
 return <details><summary>功能选项与按钮</summary><div className="sharing-form"><p className="hint">每项功能可分别调试。先修改这些选项，再保存草稿。</p><label>输出方式<select value={current.mode??'text'} onChange={e=>onChange({...current,mode:e.target.value as 'text'|'image'})}><option value="text">文稿与表格</option><option value="image">生成图片</option></select></label><label>任务框提示<textarea maxLength={600} value={current.promptPlaceholder??''} onChange={e=>onChange({...current,promptPlaceholder:e.target.value||undefined})}/></label><label>标签（用逗号分隔）<input maxLength={300} value={current.tags?.join('，')??''} onChange={e=>onChange({...current,tags:e.target.value.split(/[,，]/).map(v=>v.trim()).filter(Boolean)})}/></label>
 {current.inputs.map(f=><fieldset key={f.id}><legend>{f.label}</legend><label>选项名称<input maxLength={60} value={f.label} onChange={e=>updateInput(f.id,{label:e.target.value})}/></label><label>选项类型<select value={f.type} onChange={e=>{const type=e.target.value as FeatureInput['type'];onChange({...current,inputs:current.inputs.map(x=>x.id!==f.id?x:{id:f.id,label:f.label,type,...(type==='select'?{options:['选项一','选项二'],default:'选项一'}:type==='checkbox'?{default:false}:type==='number'?{default:0}:{})})});}}><option value="select">单选菜单</option><option value="text">文字输入</option><option value="number">数字输入</option><option value="checkbox">勾选开关</option></select></label>
 {f.type==='select'?<label>可选项（每行一项）<textarea value={f.options?.join('\n')??''} onChange={e=>updateInput(f.id,{options:e.target.value.split('\n')})}/></label>:null}{f.type==='checkbox'?<label className="sharing-check"><input type="checkbox" checked={f.default===true} onChange={e=>updateInput(f.id,{default:e.target.checked})}/>默认开启</label>:<label>默认值{f.type==='select'?<select value={String(f.default??'')} onChange={e=>updateInput(f.id,{default:e.target.value})}><option value="">不预选</option>{f.options?.map((o,i)=><option key={i}>{o}</option>)}</select>:<input type={f.type==='number'?'number':'text'} value={typeof f.default==='boolean'?'':f.default??''} onChange={e=>updateInput(f.id,{default:e.target.value===''?undefined:f.type==='number'?Number(e.target.value):e.target.value})}/>}</label>}
 {f.type==='number'?<><label>最小值<input type="number" value={f.min??''} onChange={e=>updateInput(f.id,{min:e.target.value===''?undefined:Number(e.target.value)})}/></label><label>最大值<input type="number" value={f.max??''} onChange={e=>updateInput(f.id,{max:e.target.value===''?undefined:Number(e.target.value)})}/></label></>:null}<label className="sharing-check"><input type="checkbox" checked={f.required===true} onChange={e=>updateInput(f.id,{required:e.target.checked})}/>必须填写</label><button type="button" onClick={()=>onChange({...current,inputs:current.inputs.filter(x=>x.id!==f.id)})}>移除此选项</button></fieldset>)}
 <button type="button" disabled={current.inputs.length>=12} onClick={()=>onChange({...current,inputs:[...current.inputs,{id:identifier('option_',current.inputs.map(f=>f.id)),label:'新选项',type:'text'}]})}>添加一个选项</button>
 {current.actions.map(a=><fieldset key={a.id}><legend>操作按钮 · {a.label}</legend><label>按钮文字<input maxLength={40} value={a.label} onChange={e=>onChange({...current,actions:current.actions.map(x=>x.id===a.id?{...x,label:e.target.value}:x)})}/></label><label>点击后要完成什么<textarea rows={3} maxLength={1000} value={a.instruction} onChange={e=>onChange({...current,actions:current.actions.map(x=>x.id===a.id?{...x,instruction:e.target.value}:x)})}/></label><button type="button" disabled={current.actions.length<=1} onClick={()=>onChange({...current,actions:current.actions.filter(x=>x.id!==a.id)})}>移除此按钮</button></fieldset>)}<button type="button" disabled={current.actions.length>=4} onClick={()=>onChange({...current,actions:[...current.actions,{id:identifier('action_',current.actions.map(a=>a.id)),label:'新操作',instruction:'请填写这项操作的具体交付要求'}]})}>添加一个按钮</button>
 <details><summary>使用者看到的选项预览</summary><FeatureOptions experience={current} value={featureDefaults(current)} onChange={()=>{}} disabled/></details>{value?<button type="button" onClick={()=>onChange(undefined)}>移除专属选项和按钮</button>:null}</div></details>;
}
