import './feature-skills.css';
import {useEffect,useState} from 'react';
import type {api as Api} from './oneApi';
import {featureCategories} from '../server/featureCategories';
export function OneSkillLibrary({api,onInstalled}:{api:typeof Api;onInstalled:()=>void}){
 type Item={id:string;name:string;category:string;mode:string;installed:boolean;tags:string[]};
 const [items,setItems]=useState<Item[]>([]),[selected,setSelected]=useState<string[]>([]),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const [models,setModels]=useState<{id:string;name:string;kind:string}[]>([]),[textModel,setTextModel]=useState(''),[imageModel,setImageModel]=useState('');
 useEffect(()=>{let live=true;void Promise.all([api<{items:Item[]}>('/api/admin/official-features/library'),api<{models:typeof models}>('/api/admin/official-features/options')]).then(([r,o])=>{if(live){setItems(r.items);setSelected(r.items.filter(i=>!i.installed).map(i=>i.id));setModels(o.models);}}).catch(e=>{if(live)setNotice(e.message);});return()=>{live=false;};},[api]);
 async function install(){setBusy(true);try{const r=await api<{added:string[];existing:string[]}>('/api/admin/official-features/library/install',{method:'POST',body:JSON.stringify({ids:selected,...(textModel?{textModelId:textModel}:{}),...(imageModel?{imageModelId:imageModel}:{})})});setItems(items.map(i=>r.added.includes(i.id)||r.existing.includes(i.id)?{...i,installed:true}:i));setSelected([]);setNotice(`已添加 ${r.added.length} 个草稿，可分别调试和上架。`);onInstalled();}catch(e){setNotice(e instanceof Error?e.message:'添加失败');}finally{setBusy(false);}}
 return <div className="sharing-form one-skill-library"><p>24 个 ONE 自编功能。添加不会覆盖已有配置，每个功能可独立修改提示词、选项和按钮。</p><label>文字功能模型<select value={textModel} onChange={e=>setTextModel(e.target.value)} disabled={busy}><option value="">使用已配置的默认文字模型</option>{models.filter(m=>m.kind==='chat').map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label><label>图片功能模型<select value={imageModel} onChange={e=>setImageModel(e.target.value)} disabled={busy}><option value="">使用已配置的图片模型</option>{models.filter(m=>m.kind==='image').map(m=><option value={m.id} key={m.id}>{m.name}</option>)}</select></label>
 {featureCategories.map(c=>{const rows=items.filter(i=>i.category===c.id);return rows.length?<fieldset key={c.id} disabled={busy}><legend>{c.name}</legend>{rows.map(i=><label className="sharing-check" key={i.id}><input type="checkbox" disabled={i.installed} checked={i.installed||selected.includes(i.id)} onChange={e=>setSelected(e.target.checked?[...selected,i.id]:selected.filter(id=>id!==i.id))}/>{i.name}{i.installed?' · 已添加':''}{i.mode==='image'?' · 图片':''}</label>)}</fieldset>:null;})}<button type="button" className="primary" disabled={busy||!selected.length} onClick={()=>void install()}>{busy?'正在添加…':selected.length?`添加 ${selected.length} 个功能`:'全部已添加'}</button>{notice?<p role="status">{notice}</p>:null}</div>;
}
