import { useEffect, useState } from "react";
import type { api as apiType } from "./oneApi";
import { SettingsDialog } from "./SettingsControls";
type Notice = { model: string; version: number; label: string; explanation: string; effectiveAt: string; publishedAt: string; multiplier: number; referenceInput: number; referenceOutput: number; status: string; previousInput?: number; previousOutput?: number };
const time = (date: string) => new Date(date).toLocaleString("zh-CN", { timeZone: "Asia/Shanghai", hour12: false });
export function PriceNotices({ api }: { api: typeof apiType }) {
  const [items, setItems] = useState<Notice[]>([]), [open, setOpen] = useState(false), [page, setPage] = useState(1);
  useEffect(() => { const abort = new AbortController(); const load = () => api<{ prices: { name: string; notices?: Omit<Notice, "model">[] }[] }>("/api/pricing", { signal: abort.signal }).then(r => setItems(r.prices.flatMap(m => (m.notices || []).map(n => ({ ...n, model: m.name }))).sort((a, b) => b.publishedAt.localeCompare(a.publishedAt)))).catch(() => {}); void load(); const timer = window.setInterval(() => { if (!document.hidden) void load(); }, 60000); return () => { abort.abort(); window.clearInterval(timer); }; }, [api]);
  if (!items.length) return null;
  const latest = items.find(n => n.status === "scheduled") || items[0];
  const status = (n: Notice) => n.status === "cancelled" ? "已撤回" : n.status === "scheduled" ? "即将生效" : n.status === "past" ? "历史价格" : "当前价格";
  return <><button type="button" className="price-notice-banner" onClick={() => setOpen(true)}><strong>{status(latest)} · {latest.model}</strong><span>{latest.explanation}</span><small>{time(latest.effectiveAt || latest.publishedAt)} 生效 · 北京时间 · 查看详情</small></button>{open ? <SettingsDialog title="价格通知" onClose={() => setOpen(false)}><div className="price-notice-history">{items.slice((page - 1) * 5, page * 5).map(n => <article key={`${n.model}-${n.version}`}><strong>{n.model} · {status(n)}</strong><p>{n.explanation}</p>{n.previousInput !== undefined ? <p>调整前：输入 {n.previousInput} / 输出 {n.previousOutput} 电力 / 百万 Token</p> : null}<p>调整后：输入 {Number((n.referenceInput * n.multiplier).toFixed(6))} / 输出 {Number((n.referenceOutput * n.multiplier).toFixed(6))} 电力 / 百万 Token</p><small>{time(n.effectiveAt || n.publishedAt)} 生效（北京时间） · v{n.version}</small></article>)}</div><div className="settings-pagination"><button type="button" disabled={page <= 1} onClick={() => setPage(page - 1)}>上一页</button><span>{page} / {Math.ceil(items.length / 5)}</span><button type="button" disabled={page * 5 >= items.length} onClick={() => setPage(page + 1)}>下一页</button></div></SettingsDialog> : null}</>;
}
