import {useEffect,useState} from 'react';
import type {api as Api} from './oneApi';
import type {productMetrics} from '../server/productMetrics';
import {Pagination,SearchPicker} from './SettingsControls';
type Metrics=Omit<ReturnType<typeof productMetrics>,'users'>&{users:{items:ReturnType<typeof productMetrics>['users'];total:number}};
const pct=(n:number|null)=>n===null?'—':`${(n*100).toFixed(1)}%`;
const power=(n:number)=>(n/1e6).toLocaleString('zh-CN',{maximumFractionDigits:2});
const states:Record<string,string>={active:'近 7 天活跃',at_risk:'待唤回',dormant:'沉默',never:'尚未激活'};
export function ProductMetricsPanel({api,accounts}:{api:typeof Api;accounts:{id:string;username:string;role:string;analyticsExcluded?:boolean}[]}){
  const [overrides,setOverrides]=useState<Record<string,boolean>>({});
  const [data,setData]=useState<Metrics>(),[q,setQ]=useState(''),[filter,setFilter]=useState('all'),[page,setPage]=useState(1),[refresh,setRefresh]=useState(0),[error,setError]=useState(''),[selected,setSelected]=useState(''),[excluded,setExcluded]=useState(false),[busy,setBusy]=useState(false);
  useEffect(()=>{const c=new AbortController();void api<Metrics>(`/api/admin/product-metrics?page=${page}&q=${encodeURIComponent(q)}&filter=${filter}`,{signal:c.signal}).then(d=>{setData(d);setError('');}).catch(e=>{if(!c.signal.aborted)setError(e.message);});return()=>c.abort();},[api,page,q,filter,refresh]);
  async function save(){setBusy(true);try{await api('/api/admin/product-metrics/exclusions',{method:'POST',body:JSON.stringify({userId:selected,excluded})});setOverrides(old=>({...old,[selected]:excluded}));setRefresh(n=>n+1);}catch(e){setError(e instanceof Error?e.message:'未能保存');}finally{setBusy(false);}}
  const s=data?.summary;
  const cards=s?[['累计账号',s.accounts,`自主注册 ${s.selfRegistered} · 手工开通 ${s.provisioned}`],['今日有效活跃',s.dau,`近 7 天 ${s.wau} · 近 30 天 ${s.mau}`],['近 30 天新增',s.newAccounts30,`近 7 天 ${s.newAccounts7}`],['已激活账号',s.activated,`${pct(s.accounts?s.activated/s.accounts:null)} 完成过任务`],['D1 留存',pct(s.d1.rate),`${s.d1.retained} / ${s.d1.eligible} 个成熟账号`],['D7 留存',pct(s.d7.rate),`${s.d7.retained} / ${s.d7.eligible} 个成熟账号`],['低余额待充值',s.lowBalance,'近 30 天活跃且可用电力不足 1'],['待唤回 / 沉默',`${s.atRisk} / ${s.dormant}`,`尚未激活 ${s.neverActivated}`],['近 30 天充值',`¥${s.rechargeCny30.toFixed(2)}`,`${s.payingUsers30} 人到账 · 预付款，不是收入`],['累计充值 / 复购人数',`${s.payingUsersEver} / ${s.repeatPayers}`,'复购：至少两笔微信到账充值'],['近 30 天实扣电力',power(s.consumedMicros30),`供应成本 ${power(s.costMicros30)} 电力`],['DAU / MAU',pct(s.stickiness),`匿名分享完成 ${s.anonymousQuestions30} 次，不计注册用户`]]:[];
  return <section className="product-metrics"><header className="section-toolbar"><h3>用户与增长</h3><div><button type="button" onClick={()=>setRefresh(n=>n+1)}>刷新统计</button><a className="secondary" href="/api/admin/product-metrics/export">导出近 30 天</a></div></header>
    {error?<p role="alert">{error}</p>:null}{!data?<p role="status">正在读取统计…</p>:<>
      <div className="metrics-grid">{cards.map(([title,value,hint])=><article key={String(title)}><span>{title}</span><strong>{value}</strong><small>{hint}</small></article>)}</div>
      <details className="quiet-details"><summary>统计口径 · 截至 {new Date(data.asOf).toLocaleString('zh-CN',{timeZone:'Asia/Shanghai'})}</summary>{Object.entries(data.definitions).map(([key,text])=><p key={key}>{text}</p>)}<p>已排除 {s!.excludedAccounts} 个管理员或测试账号。当前没有订阅到期数据，不显示虚构的“应续费未续费”或 MRR。</p></details>
      <details className="quiet-details"><summary>近 30 天趋势</summary><div className="metrics-table-wrap"><table><thead><tr><th>日期</th><th>有效活跃</th><th>新增账号</th><th>自主注册</th><th>到账充值</th></tr></thead><tbody>{data.daily.slice().reverse().map(d=><tr key={d.date}><td>{d.date}</td><td>{d.activeUsers}</td><td>{d.newAccounts}</td><td>{d.newSelfRegistered}</td><td>¥{d.rechargeCny.toFixed(2)}</td></tr>)}</tbody></table></div></details>
      <h4>需要关注的账号</h4><div className="metrics-filters"><input type="search" aria-label="搜索统计账号" placeholder="搜索账号" value={q} onChange={e=>{setQ(e.target.value);setPage(1);}}/><div className="settings-tabs">{[['all','全部'],['low-balance','低余额'],['at_risk','待唤回'],['dormant','沉默'],['never','未激活'],['paid','已充值']].map(([id,name])=><button type="button" key={id} aria-pressed={filter===id} onClick={()=>{setFilter(id);setPage(1);}}>{name}</button>)}</div></div>
      <div className="metrics-table-wrap"><table><thead><tr><th>账号</th><th>状态</th><th>最近使用</th><th>可用电力</th><th>到账充值</th></tr></thead><tbody>{data.users.items.map(u=><tr key={u.id}><td>{u.username}{!u.enabled?<small> · 已停用</small>:null}</td><td>{states[u.state]}{u.lowBalance?<small> · 低余额</small>:null}</td><td>{u.lastActiveDay??'—'}</td><td>{power(u.availableMicros)}</td><td>{u.rechargeCount} 次 · ¥{u.rechargeCny.toFixed(2)}</td></tr>)}</tbody></table></div>{!data.users.total?<p className="settings-empty">没有符合条件的账号</p>:null}{data.users.total>20?<Pagination size={20} page={page} total={data.users.total} onChange={setPage}/>:null}
    </>}
    <details className="quiet-details"><summary>测试账号统计范围</summary><SearchPicker label="账号" value={selected} options={accounts.filter(a=>a.role!=='admin').map(a=>({value:a.id,label:a.username}))} onChange={id=>{setSelected(id);setExcluded(overrides[id]??data?.excludedUserIds.includes(id)??accounts.find(a=>a.id===id)?.analyticsExcluded??false);}}/><label className="sharing-check"><input type="checkbox" checked={excluded} onChange={e=>setExcluded(e.target.checked)}/>排除这个测试账号（不删除数据）</label><button type="button" disabled={busy||!selected||!data} onClick={()=>void save()}>保存统计范围</button></details>
  </section>;
}
