import { useEffect, useRef, useState, type FormEvent } from "react";
import type { api as Api } from "./oneApi";
import { Pagination, SearchPicker, SettingsDialog } from "./SettingsControls";
import { MessageMarkdown } from "./MessageMarkdown";
import {PublicServicePanel} from './PublicServicePanels';
import {VisitorAccountPanel} from './VisitorAccountPanel';
import "./public-sharing.css";

type PublicationRow={id:string;version:number;slug:string;name:string;description:string;status:string;expiresAt:string;budgetMicros:number;perRunMicros:number;spent:number;held:number;attachments:boolean;sources:string[]};
type List={ready:boolean;visitorPaymentsEnabled?:boolean;items:PublicationRow[];total:number;sources:{id:string;provider:string;name:string}[]};
const power=(n:number)=>(n/1e6).toLocaleString("zh-CN",{maximumFractionDigits:6});
const failure=(e:unknown)=>e instanceof Error?e.message:"暂时未能完成";
const labels:Record<string,string>={getnote:"得到大脑",notion:"Notion",yinxiang:"印象笔记",flowus:"息流",feishu:"飞书"};
export function SharingCostHelp(){return <details className="sharing-cost-help"><summary aria-label="查看分身费用说明">?</summary><div>收费 0% 时从你的余额扣除；大于 0% 时访客登录并使用自己的电力。低于 100% 的差额由你补贴。API 和指定访客赠送仍由你承担。达到限额、到期或关闭分享后停止。</div></details>;}
export function SharingPanel({api,models,externalQuery,hideSearch=false}:{api:typeof Api;models:{id:string;name:string;kind:string}[];externalQuery?:string;hideSearch?:boolean}){
  const [data,setData]=useState<List>(),[page,setPage]=useState(1),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[receipt,setReceipt]=useState(""),[copied,setCopied]=useState('');
  const [usage,setUsage]=useState<PublicationRow>(),[usagePage,setUsagePage]=useState(1),[rows,setRows]=useState<{total:number;items:{id:string;status:string;createdAt:string;spent:number;held:number;calls:{model:string;activity:string;spent:number;status:string}[]}[]}>();
  const [draft,setDraft]=useState({name:"",description:"",prompt:"",modelId:"",sourceIds:[] as string[],attachments:true,budget:10,perRun:1,days:7,confirmed:false,visitorPercent:0,requireLogin:false,allowedUsernames:[] as string[]});
  const [services,setServices]=useState<PublicationRow>();
  const [editing,setEditing]=useState<{id:string;version:number;legacy:boolean}>();
  useEffect(()=>{if(externalQuery!==undefined){setQuery(externalQuery);setPage(1);}},[externalQuery]);
  const load=()=>api<List>(`/api/sharing/manage?page=${page}&q=${encodeURIComponent(query)}`).then(setData);
  useEffect(()=>{let live=true;void api<List>(`/api/sharing/manage?page=${page}&q=${encodeURIComponent(query)}`).then(d=>{if(live)setData(d);}).catch(e=>{if(live)setError(failure(e));});return()=>{live=false;};},[api,page,query]);
  useEffect(()=>{if(!usage)return;let live=true;setRows(undefined);void api<typeof rows>(`/api/sharing/manage/${usage.id}/usage?page=${usagePage}`).then(d=>{if(live)setRows(d);}).catch(e=>{if(live)setError(failure(e));});return()=>{live=false;};},[api,usage,usagePage]);
  async function edit(p:PublicationRow){setBusy(true);setError('');try{const config=await api<typeof draft & {version:number;legacyPrompt:boolean}>(`/api/sharing/manage/${p.id}/config`);const {name,description,prompt,modelId,sourceIds,attachments,budget,perRun,days,visitorPercent,requireLogin,allowedUsernames}=config;setDraft({name,description,prompt,modelId,sourceIds,attachments,budget,perRun,days,visitorPercent:visitorPercent??0,requireLogin:requireLogin??false,allowedUsernames:allowedUsernames??[],confirmed:false});setEditing({id:p.id,version:config.version,legacy:config.legacyPrompt});setOpen(true);}catch(e){setError(failure(e));}finally{setBusy(false);}}
  async function create(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await api<{slug:string}>(editing?`/api/sharing/manage/${editing.id}/update`:"/api/sharing/manage",{method:"POST",body:JSON.stringify({...draft,version:editing?.version})});setReceipt(`${location.origin}/s/${r.slug}`);setOpen(false);await load();}catch(e){setError(failure(e));}finally{setBusy(false);}}
  async function close(p:PublicationRow){if(!confirm(`关闭“${p.name}”的分享？链接将停止服务。`))return;setBusy(true);try{await api(`/api/sharing/manage/${p.id}/close`,{method:"POST"});await load();}catch(e){setError(failure(e));}finally{setBusy(false);}}
  return <section className="sharing-panel market-section"><header><div><h3>我的分身</h3></div><button type="button" className="primary" disabled={!data?.ready||busy} onClick={()=>{setEditing(undefined);setError('');setDraft({name:"",description:"",prompt:"",modelId:models.find(m=>m.kind==="chat")?.id||"",sourceIds:[],attachments:true,budget:10,perRun:1,days:7,confirmed:false,visitorPercent:0,requireLogin:false,allowedUsernames:[]});setOpen(true);}}>＋ 创建分身</button></header>
    {data?.ready===false?<p role="status">分享功能准备中，请管理员完成数据库升级。</p>:null}
    {!hideSearch?<input aria-label="搜索分享分身" placeholder="搜索分身" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/>:null}
    {receipt?<div className="sharing-receipt"><strong>分享链接</strong><input readOnly aria-label="分享链接" value={receipt}/><button type="button" onClick={()=>void navigator.clipboard.writeText(receipt).then(()=>setCopied(receipt)).catch(()=>setError("请选中链接复制"))}>{copied===receipt?'已复制':'复制链接'}</button></div>:null}
    <div className="sharing-list">{data?.items.map(p=><article key={p.id}><header><strong>{p.name} · v{p.version??1}</strong><span>{p.status==="closed"?"已关闭":Date.parse(p.expiresAt)<Date.now()?"已到期":"分享中"}</span></header><p>{p.description}</p><p>已用 {power(p.spent)} / {power(p.budgetMicros)} 电力{p.held?` · 预留 ${power(p.held)}`:""}</p><details><summary>权限与额度</summary><p>仅问答{p.attachments?" · 支持访客附件":""}</p><p>知识来源：{p.sources.join("、")||"未分享知识"}</p><p>单次上限 {power(p.perRunMicros)} 电力 · 到期 {new Date(p.expiresAt).toLocaleString()}</p><p>更新配置可保留原链接，历史消耗不会清零。</p></details><footer><button onClick={()=>setReceipt(`${location.origin}/s/${p.slug}`)}>分享链接</button><button onClick={()=>{setUsage(p);setUsagePage(1);}}>用量详情</button>{p.status==="active"?<><button disabled={busy} onClick={()=>void edit(p)}>更新配置</button><button disabled={busy} onClick={()=>void close(p)}>关闭分享</button></>:null}</footer></article>)}</div>
    <details hidden={!data?.items.length}><summary>API、访客赠送与收益</summary><div className="settings-choice-list">{data?.items.map(p=><button type="button" key={p.id} onClick={()=>setServices(p)}>{p.name} · 管理接入与账本</button>)}</div></details>
    {services?<SettingsDialog title={`${services.name} · 接入与收益`} onClose={()=>setServices(undefined)}><PublicServicePanel api={api} publication={services}/></SettingsDialog>:null}
    {data&&data.total>10?<Pagination page={page} total={data.total} onChange={setPage}/>:null}{error?<p role="alert">{error}</p>:null}
    {data?.ready && !data.total ? <p className="sharing-empty">{query?'没有匹配的分身':'还没有创建分身'}</p> : null}
    {open?<SettingsDialog title={editing?`更新分身 · v${editing.version}`:"创建分身"} onClose={()=>{if(!busy)setOpen(false);}}><form className="sharing-form" onSubmit={create}>
      {editing?<><p className="hint">更新后原链接不变，历史消耗不清零。访客需重新开始，新版不会带入旧会话资料。有效期从本次发布起算；有问题正在回答时暂不能更新。</p>{editing.legacy?<p role="alert">这是旧版发布记录，请重新填写回答要求；旧系统提示词不会重复叠加。</p>:null}<PublicationHistory api={api} id={editing.id}/></>:null}
      <label>名称<input required maxLength={60} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
      <label>介绍<input maxLength={300} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
      <label>回答要求<textarea rows={5} maxLength={12000} value={draft.prompt} onChange={e=>setDraft({...draft,prompt:e.target.value})} placeholder="这个分身擅长什么，如何回答？"/></label>
      <div className="sharing-model-field"><span>问答模型</span><SearchPicker label="问答模型" value={draft.modelId} options={models.filter(m=>m.kind==="chat").map(m=>({value:m.id,label:m.name}))} onChange={modelId=>setDraft({...draft,modelId})}/></div>
      <fieldset><legend>分享哪些知识</legend>{data?.sources.map(s=><label className="sharing-check" key={s.id}><input type="checkbox" checked={draft.sourceIds.includes(s.id)} onChange={e=>setDraft({...draft,sourceIds:e.target.checked?[...draft.sourceIds,s.id]:draft.sourceIds.filter(id=>id!==s.id)})}/>{labels[s.provider]||s.provider} · {s.name}</label>)}<small>勾选后允许访客提问并检索该连接的全部已授权资料，不是单篇文档。未勾选的来源不会读取。</small></fieldset>
      <label className="sharing-check"><input type="checkbox" checked={draft.attachments} onChange={e=>setDraft({...draft,attachments:e.target.checked})}/>允许访客上传附件用于问答</label>
      {draft.sourceIds.filter(id=>!data?.sources.some(s=>s.id===id)).map(id=><p key={id}>一个原知识连接已不可用。<button type="button" onClick={()=>setDraft({...draft,sourceIds:draft.sourceIds.filter(s=>s!==id)})}>移除该来源</button></p>)}
      <details><summary>访客收费与访问范围 · {draft.visitorPercent?`${draft.visitorPercent}%`:'我请客'}</summary><label>访客按 ONE 基础费用的多少百分比消费<input type="number" min="0" max="1000" step="1" value={draft.visitorPercent} onChange={e=>setDraft({...draft,visitorPercent:Number(e.target.value)})}/></label><p className="hint">0 表示你请客；100 表示访客承担基础费用；120 表示加价 20%。加价收益只在实际消费后形成，暂不提现。</p>{!data?.visitorPaymentsEnabled?<p>管理员尚未启用访客付费，目前只能设置 0%。</p>:null}<label><input type="checkbox" checked={draft.requireLogin} onChange={e=>setDraft({...draft,requireLogin:e.target.checked})}/>要求访客登录账号</label><label>仅这些已注册账号可以访问（每行一个，留空不限定）<textarea rows={3} value={draft.allowedUsernames.join('\n')} onChange={e=>setDraft({...draft,allowedUsernames:e.target.value.split('\n')})}/></label></details>
      <section className="sharing-budget"><header><span>使用额度</span><SharingCostHelp/></header><div className="sharing-grid"><label>总电力<input type="number" min="0.01" max="10000" step="0.01" required value={draft.budget} onChange={e=>setDraft({...draft,budget:Number(e.target.value)})}/></label><label>单次电力<input type="number" min="0.01" max={draft.budget} step="0.01" required value={draft.perRun} onChange={e=>setDraft({...draft,perRun:Number(e.target.value)})}/></label><label>有效天数<input type="number" min="1" max="90" required value={draft.days} onChange={e=>setDraft({...draft,days:Number(e.target.value)})}/></label></div></section>
      <label className="sharing-check"><input required type="checkbox" checked={draft.confirmed} onChange={e=>setDraft({...draft,confirmed:e.target.checked})}/>确认知识范围、收费方式和费用承担规则</label>
      {error?<p role="alert">{error}</p>:null}<button className="primary" disabled={busy||!draft.modelId}>{busy?"正在发布…":editing?"确认更新，保留原链接":"发布并生成链接"}</button>
    </form></SettingsDialog>:null}
    {usage?<SettingsDialog title={`${usage.name} · 用量`} onClose={()=>setUsage(undefined)}><p>仅显示任务状态和费用，不展示访客原文或附件。</p>{rows?.items.map(r=><details key={r.id}><summary>{new Date(r.createdAt).toLocaleString()} · {({completed:"完成",running:"进行中",failed:"未完成",interrupted:"已中断"} as Record<string,string>)[r.status]} · {power(r.spent)} 电力</summary><p>任务编号 {r.id}</p><p>预留 {power(r.held)} 电力</p>{r.calls?.map((c,i)=><p key={i}>{c.activity} · {c.model} · {power(c.spent)} 电力</p>)}</details>)}{rows?<Pagination page={usagePage} total={rows.total} onChange={setUsagePage}/>:<p>正在加载…</p>}</SettingsDialog>:null}
  </section>;
}

function PublicationHistory({api,id}:{api:typeof Api;id:string}){
  const [page,setPage]=useState(1),[open,setOpen]=useState(false),[error,setError]=useState(''),[data,setData]=useState<{total:number;history:{version:number;name:string;prompt:string;legacyPrompt:boolean;updatedAt:string;budget:number;perRun:number}[]}>();
  useEffect(()=>{if(!open)return;let active=true;void api<typeof data>(`/api/sharing/manage/${id}/config?page=${page}`).then(v=>{if(active)setData(v);}).catch(e=>{if(active)setError(failure(e));});return()=>{active=false;};},[api,id,page,open]);
  return <details onToggle={e=>setOpen(e.currentTarget.open)}><summary>历史配置（保留最近 20 版）</summary>{data?.history.map(v=><details key={v.version}><summary>v{v.version} · {v.name} · {new Date(v.updatedAt).toLocaleString()}</summary><p>总额度 {v.budget} · 单次 {v.perRun} 电力</p><p style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{v.legacyPrompt?'旧版未独立保存用户回答要求':v.prompt||'未填写额外回答要求'}</p></details>)}{data&&!data.total?<p>暂无历史版本</p>:null}<button type="button" disabled={page<=1} onClick={()=>setPage(page-1)}>上一页</button><span> {page} </span><button type="button" disabled={!data||page*5>=data.total} onClick={()=>setPage(page+1)}>下一页</button>{error?<p role="alert">{error}</p>:null}</details>;
}
type Run={id:string;operationId:string;content:string;response?:string;status:string;finishReason?:string;error?:string;warning?:string;createdAt:string;chargedMicros?:number};
type FileItem={id:string;originalName:string;status?:string;parseError?:string};
export function PublicSharingPage({slug}:{slug:string}){
  const [meta,setMeta]=useState<{name:string;description:string;attachments:boolean;version:number;visitorPercent:number;requireLogin:boolean;paymentEnabled:boolean}>(),[token,setToken]=useState(()=>{try{return sessionStorage.getItem(`one-guest:${slug}`)||"";}catch{return "";}}),[items,setItems]=useState<Run[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[text,setText]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[files,setFiles]=useState<FileItem[]>([]),[retry,setRetry]=useState<{operationId:string;content:string;attachmentIds:string[];confirmedPriceVersion?:number;confirmedPayment?:boolean}>(),[paymentConfirmed,setPaymentConfirmed]=useState(false);
  const live=useRef(true), tokenRef=useRef(token);tokenRef.current=token;
  const base=`/api/sharing/${encodeURIComponent(slug)}`;
  async function request<T>(path:string,options:RequestInit={},auth=tokenRef.current):Promise<T>{const headers=new Headers(options.headers);if(auth)headers.set("Authorization",`Bearer ${auth}`);if(!headers.has("Content-Type"))headers.set("Content-Type","application/json");const r=await fetch(base+path,{...options,headers,credentials:"same-origin"});const d=await r.json();if(!r.ok){if((d.code==='PUBLICATION_UPDATED'||d.code==='VISITOR_LOGIN_REQUIRED')&&live.current){setItems([]);setFiles([]);setRetry(undefined);}throw Object.assign(new Error(d.error||"暂时无法访问"),{status:r.status});}return d;}
  async function load(){const d=await request<{items:Run[];total:number}>(`/session?page=${page}`);if(live.current){setItems(d.items);setTotal(d.total);}}
  useEffect(()=>{live.current=true;void request<typeof meta>("",{},"").then(d=>{if(live.current)setMeta(d);}).catch(e=>{if(live.current)setError(failure(e));});return()=>{live.current=false;};},[slug]);
  useEffect(()=>{if(!token)return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const d=await request<{items:Run[];total:number}>(`/session?page=${page}`);if(cancelled)return;setItems(d.items);setTotal(d.total);if(d.items.some(r=>r.status==="running"))timer=setTimeout(poll,2500);}catch(e){if(!cancelled)setError(failure(e));}}void poll();return()=>{cancelled=true;clearTimeout(timer);};},[token,page,busy]);
  async function start(){setBusy(true);setError("");try{const fresh=await request<typeof meta>("",{},"");setMeta(fresh);const d=await request<{token:string}>("/sessions",{method:"POST"},"");tokenRef.current=d.token;setToken(d.token);try{sessionStorage.setItem(`one-guest:${slug}`,d.token);}catch{}setItems([]);setPage(1);setFiles([]);setRetry(undefined);}catch(e){setError(failure(e));}finally{setBusy(false);}}
  async function send(e:FormEvent){e.preventDefault();if(!text.trim()&&!retry)return;setBusy(true);setError("");const payload=retry||{operationId:crypto.randomUUID(),content:text.trim(),attachmentIds:files.map(f=>f.id),confirmedPriceVersion:meta?.version,confirmedPayment:paymentConfirmed};setRetry(payload);try{await request("/questions",{method:"POST",body:JSON.stringify(payload)});setRetry(undefined);setText("");setFiles([]);setPage(1);await load();}catch(e){if(e && typeof e==="object" && "status" in e && [400,401,402,403,404,410,413,422,429].includes(Number(e.status)))setRetry(undefined);setError(failure(e));}finally{setBusy(false);}}
  async function upload(selected:FileList|null){if(!selected)return;setUploading(true);setError("");try{if(selected.length+files.length>5)throw new Error("每条消息最多 5 个附件");for(const file of Array.from(selected)){const created=await request<{attachment:FileItem}>("/uploads",{method:"POST",body:JSON.stringify({name:file.name,size:file.size,mimeType:file.type})});const id=created.attachment.id;setFiles(current=>[...current,created.attachment]);for(let offset=0;offset<file.size;offset+=4*1024**2){await request(`/uploads/${id}/chunks?offset=${offset}`,{method:"PUT",headers:{"Content-Type":"application/octet-stream"},body:file.slice(offset,offset+4*1024**2)});}await request(`/uploads/${id}/complete`,{method:"POST"});}}catch(e){setFiles(current=>current.map(f=>f.status==="uploading"?{...f,status:"failed",parseError:"上传未完成，请移除后重试"}:f));setError(failure(e));}finally{setUploading(false);}}
  useEffect(()=>{const pending=files.filter(f=>!["ready","failed"].includes(f.status||""));if(!pending.length||uploading)return;let cancelled=false;const timer=setTimeout(()=>void Promise.all(pending.map(async f=>(await request<{attachment:FileItem}>(`/uploads/${f.id}`)).attachment)).then(results=>{if(!cancelled)setFiles(current=>current.map(f=>results.find(r=>r.id===f.id)||f));}).catch(e=>{if(!cancelled){setError(failure(e));setFiles(current=>current.map(f=>pending.some(p=>p.id===f.id)?{...f,status:"failed"}:f));}}),2000);return()=>{cancelled=true;clearTimeout(timer);};},[files,uploading,token]);
  const running=items.some(r=>r.status==="running");
  return <main className="public-sharing-page"><header><span>ONE · 分享分身</span><h1>{meta?.name||"正在打开…"}</h1><p>{meta?.description}</p></header>
    <p className="sharing-privacy">你的问题与附件会交给 AI 服务处理，不会展示给发布者。{meta?.visitorPercent?`当前收费为 ONE 基础费用的 ${meta.visitorPercent}%，实际消耗从你的电力扣除；指定赠送额度优先由发布者承担。`:'费用由发布者承担。'}</p>
    <VisitorAccountPanel required={!!meta?.requireLogin} onChanged={()=>{setToken('');tokenRef.current='';setItems([]);setFiles([]);setRetry(undefined);setPaymentConfirmed(false);setError('');try{sessionStorage.removeItem(`one-guest:${slug}`);}catch{}}}/>
    {meta?.visitorPercent?<label><input type="checkbox" checked={paymentConfirmed} onChange={e=>setPaymentConfirmed(e.target.checked)}/>我确认当前版本的收费百分比，并承担实际消耗</label>:null}
    {!token?<button className="primary" disabled={!meta||busy} onClick={()=>void start()}>开始提问</button>:<>
      <div className="public-answers">{items.slice().reverse().map(r=><article key={r.id}><p className="public-question">{r.content}</p><div className="markdown-body"><MessageMarkdown allowImages={false}>{r.response||r.error||(r.status==="running"?"正在回答…":"未完成")}</MessageMarkdown></div>{r.status!=='running'?<small>本次消耗 {(r.chargedMicros??0)/1e6} 电力{!r.chargedMicros?'（由发布者承担，或没有产生已结算费用）':''}</small>:null}{r.warning?<p role="status">{r.warning}</p>:null}{r.finishReason==="length"?<p>本次回答达到长度上限，可发送“继续”接着提问。</p>:null}</article>)}</div>
      {total>10?<Pagination page={page} total={total} onChange={setPage}/>:null}
      <form className="public-composer" onSubmit={send}><textarea aria-label="问题" rows={3} maxLength={6000} value={text} onChange={e=>setText(e.target.value)} disabled={!!retry} placeholder="问我一件事…"/>
        {files.map(f=><div className="sharing-file" key={f.id}><span>{f.originalName} · {f.status==="ready"?"已就绪":f.status==="failed"?f.parseError||"未完成":"处理中…"}</span><button type="button" disabled={uploading||busy||!!retry} onClick={()=>setFiles(current=>current.filter(x=>x.id!==f.id))}>移除</button></div>)}
        <footer>{meta?.attachments?<label className="sharing-upload">添加附件<input type="file" multiple accept=".pdf,.docx,.pptx,.xlsx,.xls,.csv,.txt,.md,.json,.png,.jpg,.jpeg,.webp,.gif" disabled={busy||uploading||running||!!retry} onChange={e=>{void upload(e.target.files);e.target.value="";}}/></label>:null}<button className="primary" disabled={busy||uploading||running||files.some(f=>f.status!=="ready")||(!text.trim()&&!retry)||!!meta?.visitorPercent&&!paymentConfirmed}>{retry?"检查上次提交":"发送"}</button></footer>
        {meta?.attachments?<small>最多 5 个附件，单文件 200 MB；图片 20 MB。只用于本会话问答。</small>:null}
      </form></>}
    {error?<div role="alert"><p>{error}</p>{token?<button disabled={busy||uploading||running} onClick={()=>{if(confirm("重新开始会创建独立访客会话，旧会话不会带入。"))void start();}}>重新开始</button>:null}</div>:null}
  </main>;
}
