import { useEffect, useRef, useState, type FormEvent } from "react";
import type { api as Api } from "./oneApi";
import { Pagination, SearchPicker, SettingsDialog } from "./SettingsControls";
import { MessageMarkdown } from "./MessageMarkdown";
import "./public-sharing.css";

type PublicationRow={id:string;slug:string;name:string;description:string;status:string;expiresAt:string;budgetMicros:number;perRunMicros:number;spent:number;held:number;attachments:boolean;sources:string[]};
type List={ready:boolean;items:PublicationRow[];total:number;sources:{id:string;provider:string;name:string}[]};
const power=(n:number)=>(n/1e6).toLocaleString("zh-CN",{maximumFractionDigits:6});
const failure=(e:unknown)=>e instanceof Error?e.message:"暂时未能完成";
const labels:Record<string,string>={getnote:"得到大脑",notion:"Notion",yinxiang:"印象笔记",flowus:"息流",feishu:"飞书"};
export function SharingPanel({api,models}:{api:typeof Api;models:{id:string;name:string;kind:string}[]}){
  const [data,setData]=useState<List>(),[page,setPage]=useState(1),[query,setQuery]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[open,setOpen]=useState(false),[receipt,setReceipt]=useState("");
  const [usage,setUsage]=useState<PublicationRow>(),[usagePage,setUsagePage]=useState(1),[rows,setRows]=useState<{total:number;items:{id:string;status:string;createdAt:string;spent:number;held:number;calls:{model:string;activity:string;spent:number;status:string}[]}[]}>();
  const [draft,setDraft]=useState({name:"",description:"",prompt:"",modelId:"",sourceIds:[] as string[],attachments:true,budget:10,perRun:1,days:7,confirmed:false});
  const load=()=>api<List>(`/api/sharing/manage?page=${page}&q=${encodeURIComponent(query)}`).then(setData);
  useEffect(()=>{let live=true;void api<List>(`/api/sharing/manage?page=${page}&q=${encodeURIComponent(query)}`).then(d=>{if(live)setData(d);}).catch(e=>{if(live)setError(failure(e));});return()=>{live=false;};},[api,page,query]);
  useEffect(()=>{if(!usage)return;let live=true;setRows(undefined);void api<typeof rows>(`/api/sharing/manage/${usage.id}/usage?page=${usagePage}`).then(d=>{if(live)setRows(d);}).catch(e=>{if(live)setError(failure(e));});return()=>{live=false;};},[api,usage,usagePage]);
  async function create(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const r=await api<{slug:string}>("/api/sharing/manage",{method:"POST",body:JSON.stringify(draft)});setReceipt(`${location.origin}/s/${r.slug}`);setOpen(false);await load();}catch(e){setError(failure(e));}finally{setBusy(false);}}
  async function close(p:PublicationRow){if(!confirm(`关闭“${p.name}”的分享？链接将停止服务。`))return;setBusy(true);try{await api(`/api/sharing/manage/${p.id}/close`,{method:"POST"});await load();}catch(e){setError(failure(e));}finally{setBusy(false);}}
  return <section className="sharing-panel"><header><h3>分享分身</h3><button type="button" className="primary" disabled={!data?.ready||busy} onClick={()=>{setDraft({name:"",description:"",prompt:"",modelId:models.find(m=>m.kind==="chat")?.id||"",sourceIds:[],attachments:true,budget:10,perRun:1,days:7,confirmed:false});setOpen(true);}}>新建分享</button></header>
    {data?.ready===false?<p role="status">分享功能准备中，请管理员完成数据库升级。</p>:null}
    <input aria-label="搜索分享分身" placeholder="搜索分身" value={query} onChange={e=>{setQuery(e.target.value);setPage(1);}}/>
    {receipt?<div className="sharing-receipt"><strong>分享链接</strong><input readOnly aria-label="分享链接" value={receipt}/><button onClick={()=>void navigator.clipboard.writeText(receipt).catch(()=>setError("请选中链接复制"))}>复制链接</button></div>:null}
    <div className="sharing-list">{data?.items.map(p=><article key={p.id}><header><strong>{p.name}</strong><span>{p.status==="closed"?"已关闭":Date.parse(p.expiresAt)<Date.now()?"已到期":"分享中"}</span></header><p>{p.description}</p><p>已用 {power(p.spent)} / {power(p.budgetMicros)} 电力{p.held?` · 预留 ${power(p.held)}`:""}</p><details><summary>权限与额度</summary><p>仅问答{p.attachments?" · 支持访客附件":""}</p><p>知识来源：{p.sources.join("、")||"未分享知识"}</p><p>单次上限 {power(p.perRunMicros)} 电力 · 到期 {new Date(p.expiresAt).toLocaleString()}</p><p>发布内容固定。修改提示词或知识范围，请关闭后重新发布。</p></details><footer><button onClick={()=>setReceipt(`${location.origin}/s/${p.slug}`)}>分享链接</button><button onClick={()=>{setUsage(p);setUsagePage(1);}}>用量详情</button>{p.status==="active"?<button disabled={busy} onClick={()=>void close(p)}>关闭分享</button>:null}</footer></article>)}</div>
    {data?<Pagination page={page} total={data.total} onChange={setPage}/>:null}{error?<p role="alert">{error}</p>:null}
    {open?<SettingsDialog title="发布问答分身" onClose={()=>{if(!busy)setOpen(false);}}><form className="sharing-form" onSubmit={create}>
      <label>名称<input required maxLength={60} value={draft.name} onChange={e=>setDraft({...draft,name:e.target.value})}/></label>
      <label>介绍<input maxLength={300} value={draft.description} onChange={e=>setDraft({...draft,description:e.target.value})}/></label>
      <label>回答要求<textarea rows={5} maxLength={12000} value={draft.prompt} onChange={e=>setDraft({...draft,prompt:e.target.value})} placeholder="这个分身擅长什么，如何回答？"/></label>
      <SearchPicker label="问答模型" value={draft.modelId} options={models.filter(m=>m.kind==="chat").map(m=>({value:m.id,label:m.name}))} onChange={modelId=>setDraft({...draft,modelId})}/>
      <fieldset><legend>分享哪些知识</legend>{data?.sources.map(s=><label className="sharing-check" key={s.id}><input type="checkbox" checked={draft.sourceIds.includes(s.id)} onChange={e=>setDraft({...draft,sourceIds:e.target.checked?[...draft.sourceIds,s.id]:draft.sourceIds.filter(id=>id!==s.id)})}/>{labels[s.provider]||s.provider} · {s.name}</label>)}<small>勾选后允许访客提问并检索该连接的全部已授权资料，不是单篇文档。未勾选的来源不会读取。</small></fieldset>
      <label className="sharing-check"><input type="checkbox" checked={draft.attachments} onChange={e=>setDraft({...draft,attachments:e.target.checked})}/>允许访客上传附件用于问答</label>
      <div className="sharing-grid"><label>总电力上限<input type="number" min="0.01" max="10000" step="0.01" required value={draft.budget} onChange={e=>setDraft({...draft,budget:Number(e.target.value)})}/></label><label>每次提问上限<input type="number" min="0.01" max={draft.budget} step="0.01" required value={draft.perRun} onChange={e=>setDraft({...draft,perRun:Number(e.target.value)})}/></label><label>有效天数<input type="number" min="1" max="90" required value={draft.days} onChange={e=>setDraft({...draft,days:Number(e.target.value)})}/></label></div>
      <p>链接可转发；费用从你的电力余额扣除，Key 拔掉后仍可问答。仅开放问答和访客附件，不开放其他工具。</p>
      <label className="sharing-check"><input required type="checkbox" checked={draft.confirmed} onChange={e=>setDraft({...draft,confirmed:e.target.checked})}/>确认知识范围并承担上述限额内的费用</label>
      {error?<p role="alert">{error}</p>:null}<button className="primary" disabled={busy||!draft.modelId}>{busy?"正在发布…":"发布并生成链接"}</button>
    </form></SettingsDialog>:null}
    {usage?<SettingsDialog title={`${usage.name} · 用量`} onClose={()=>setUsage(undefined)}><p>仅显示任务状态和费用，不展示访客原文或附件。</p>{rows?.items.map(r=><details key={r.id}><summary>{new Date(r.createdAt).toLocaleString()} · {({completed:"完成",running:"进行中",failed:"未完成",interrupted:"已中断"} as Record<string,string>)[r.status]} · {power(r.spent)} 电力</summary><p>任务编号 {r.id}</p><p>预留 {power(r.held)} 电力</p>{r.calls?.map((c,i)=><p key={i}>{c.activity} · {c.model} · {power(c.spent)} 电力</p>)}</details>)}{rows?<Pagination page={usagePage} total={rows.total} onChange={setUsagePage}/>:<p>正在加载…</p>}</SettingsDialog>:null}
  </section>;
}

type Run={id:string;operationId:string;content:string;response?:string;status:string;finishReason?:string;error?:string;warning?:string;createdAt:string};
type FileItem={id:string;originalName:string;status?:string;parseError?:string};
export function PublicSharingPage({slug}:{slug:string}){
  const [meta,setMeta]=useState<{name:string;description:string;attachments:boolean}>(),[token,setToken]=useState(()=>{try{return sessionStorage.getItem(`one-guest:${slug}`)||"";}catch{return "";}}),[items,setItems]=useState<Run[]>([]),[page,setPage]=useState(1),[total,setTotal]=useState(0),[text,setText]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false),[uploading,setUploading]=useState(false),[files,setFiles]=useState<FileItem[]>([]),[retry,setRetry]=useState<{operationId:string;content:string;attachmentIds:string[]}>();
  const live=useRef(true), tokenRef=useRef(token);tokenRef.current=token;
  const base=`/api/sharing/${encodeURIComponent(slug)}`;
  async function request<T>(path:string,options:RequestInit={},auth=tokenRef.current):Promise<T>{const headers=new Headers(options.headers);if(auth)headers.set("Authorization",`Bearer ${auth}`);if(!headers.has("Content-Type"))headers.set("Content-Type","application/json");const r=await fetch(base+path,{...options,headers,credentials:"omit"});const d=await r.json();if(!r.ok)throw Object.assign(new Error(d.error||"暂时无法访问"),{status:r.status});return d;}
  async function load(){const d=await request<{items:Run[];total:number}>(`/session?page=${page}`);if(live.current){setItems(d.items);setTotal(d.total);}}
  useEffect(()=>{live.current=true;void request<typeof meta>("",{},"").then(d=>{if(live.current)setMeta(d);}).catch(e=>{if(live.current)setError(failure(e));});return()=>{live.current=false;};},[slug]);
  useEffect(()=>{if(!token)return;let cancelled=false;let timer:ReturnType<typeof setTimeout>;async function poll(){try{const d=await request<{items:Run[];total:number}>(`/session?page=${page}`);if(cancelled)return;setItems(d.items);setTotal(d.total);if(d.items.some(r=>r.status==="running"))timer=setTimeout(poll,2500);}catch(e){if(!cancelled)setError(failure(e));}}void poll();return()=>{cancelled=true;clearTimeout(timer);};},[token,page,busy]);
  async function start(){setBusy(true);setError("");try{const d=await request<{token:string}>("/sessions",{method:"POST"},"");tokenRef.current=d.token;setToken(d.token);try{sessionStorage.setItem(`one-guest:${slug}`,d.token);}catch{}setItems([]);setPage(1);setFiles([]);setRetry(undefined);}catch(e){setError(failure(e));}finally{setBusy(false);}}
  async function send(e:FormEvent){e.preventDefault();if(!text.trim()&&!retry)return;setBusy(true);setError("");const payload=retry||{operationId:crypto.randomUUID(),content:text.trim(),attachmentIds:files.map(f=>f.id)};setRetry(payload);try{await request("/questions",{method:"POST",body:JSON.stringify(payload)});setRetry(undefined);setText("");setFiles([]);setPage(1);await load();}catch(e){if(e && typeof e==="object" && "status" in e && [400,401,402,403,404,410,413,422,429].includes(Number(e.status)))setRetry(undefined);setError(failure(e));}finally{setBusy(false);}}
  async function upload(selected:FileList|null){if(!selected)return;setUploading(true);setError("");try{if(selected.length+files.length>5)throw new Error("每条消息最多 5 个附件");for(const file of Array.from(selected)){const created=await request<{attachment:FileItem}>("/uploads",{method:"POST",body:JSON.stringify({name:file.name,size:file.size,mimeType:file.type})});const id=created.attachment.id;setFiles(current=>[...current,created.attachment]);for(let offset=0;offset<file.size;offset+=4*1024**2){await request(`/uploads/${id}/chunks?offset=${offset}`,{method:"PUT",headers:{"Content-Type":"application/octet-stream"},body:file.slice(offset,offset+4*1024**2)});}await request(`/uploads/${id}/complete`,{method:"POST"});}}catch(e){setFiles(current=>current.map(f=>f.status==="uploading"?{...f,status:"failed",parseError:"上传未完成，请移除后重试"}:f));setError(failure(e));}finally{setUploading(false);}}
  useEffect(()=>{const pending=files.filter(f=>!["ready","failed"].includes(f.status||""));if(!pending.length||uploading)return;let cancelled=false;const timer=setTimeout(()=>void Promise.all(pending.map(async f=>(await request<{attachment:FileItem}>(`/uploads/${f.id}`)).attachment)).then(results=>{if(!cancelled)setFiles(current=>current.map(f=>results.find(r=>r.id===f.id)||f));}).catch(e=>{if(!cancelled){setError(failure(e));setFiles(current=>current.map(f=>pending.some(p=>p.id===f.id)?{...f,status:"failed"}:f));}}),2000);return()=>{cancelled=true;clearTimeout(timer);};},[files,uploading,token]);
  const running=items.some(r=>r.status==="running");
  return <main className="public-sharing-page"><header><span>ONE · 分享分身</span><h1>{meta?.name||"正在打开…"}</h1><p>{meta?.description}</p></header>
    <p className="sharing-privacy">仅用于问答。你的问题与附件会交给 AI 服务处理，不会展示给发布者；费用由发布者承担。请勿上传无权分享的敏感资料。</p>
    {!token?<button className="primary" disabled={!meta||busy} onClick={()=>void start()}>开始提问</button>:<>
      <div className="public-answers">{items.slice().reverse().map(r=><article key={r.id}><p className="public-question">{r.content}</p><div className="markdown-body"><MessageMarkdown allowImages={false}>{r.response||r.error||(r.status==="running"?"正在回答…":"未完成")}</MessageMarkdown></div>{r.warning?<p role="status">{r.warning}</p>:null}{r.finishReason==="length"?<p>本次回答达到长度上限，可发送“继续”接着提问。</p>:null}</article>)}</div>
      {total>10?<Pagination page={page} total={total} onChange={setPage}/>:null}
      <form className="public-composer" onSubmit={send}><textarea aria-label="问题" rows={3} maxLength={6000} value={text} onChange={e=>setText(e.target.value)} disabled={!!retry} placeholder="问我一件事…"/>
        {files.map(f=><div className="sharing-file" key={f.id}><span>{f.originalName} · {f.status==="ready"?"已就绪":f.status==="failed"?f.parseError||"未完成":"处理中…"}</span><button type="button" disabled={uploading||busy||!!retry} onClick={()=>setFiles(current=>current.filter(x=>x.id!==f.id))}>移除</button></div>)}
        <footer>{meta?.attachments?<label className="sharing-upload">添加附件<input type="file" multiple accept=".pdf,.docx,.pptx,.xlsx,.xls,.csv,.txt,.md,.json,.png,.jpg,.jpeg,.webp,.gif" disabled={busy||uploading||running||!!retry} onChange={e=>{void upload(e.target.files);e.target.value="";}}/></label>:null}<button className="primary" disabled={busy||uploading||running||files.some(f=>f.status!=="ready")||(!text.trim()&&!retry)}>{retry?"检查上次提交":"发送"}</button></footer>
        {meta?.attachments?<small>最多 5 个附件，单文件 200 MB；图片 20 MB。只用于本会话问答。</small>:null}
      </form></>}
    {error?<div role="alert"><p>{error}</p>{token?<button disabled={busy||uploading||running} onClick={()=>{if(confirm("重新开始会创建独立访客会话，旧会话不会带入。"))void start();}}>重新开始</button>:null}</div>:null}
  </main>;
}
