import {useEffect,useState} from 'react';
import type {api as Api} from './oneApi';
import {Pagination} from './SettingsControls';
const power=(n:number)=>(n/1e6).toLocaleString('zh-CN',{maximumFractionDigits:6});
type Publication={id:string;version:number;budgetMicros:number;perRunMicros:number};
export function PublicServicePanel({api,publication:p}:{api:typeof Api;publication:Publication}){
  const [page,setPage]=useState(1),[items,setItems]=useState<{id:string;name:string;version:number;status:string;budgetMicros:number;spent:number;expiresAt:string}[]>([]),[total,setTotal]=useState(0),[name,setName]=useState(''),[budget,setBudget]=useState(Math.min(1,p.budgetMicros/1e6)),[perRun,setPerRun]=useState(Math.min(.1,p.perRunMicros/1e6)),[days,setDays]=useState(7),[confirmed,setConfirmed]=useState(false),[token,setToken]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  async function load(){try{const r=await api<{items:typeof items;total:number}>(`/api/sharing-api/manage/${p.id}/keys?page=${page}`);setItems(r.items);setTotal(r.total);}catch(e){setMessage(e instanceof Error?e.message:'无法读取密钥');}}
  useEffect(()=>{void load();},[api,p.id,page]);
  async function issue(){setBusy(true);setMessage('');try{const r=await api<{token:string}>(`/api/sharing-api/manage/${p.id}/keys`,{method:'POST',body:JSON.stringify({version:p.version??1,name,budget,perRun,days,confirmed})});setToken(r.token);setConfirmed(false);await load();}catch(e){setMessage(e instanceof Error?e.message:'签发失败');}finally{setBusy(false);}}
  async function revoke(id:string){setBusy(true);try{await api(`/api/sharing-api/manage/${p.id}/keys/${id}/revoke`,{method:'POST'});await load();}catch(e){setMessage(e instanceof Error?e.message:'撤销失败');}finally{setBusy(false);}}
  return <div className="sharing-form"><details open><summary>API 接入</summary><p className="hint">每次提交一个问题，返回一个任务编号，再查询回答。API 费用由你承担，额度同时受分身总额度约束；更新分身后需签发新版密钥。</p><label>用途名称<input maxLength={60} value={name} onChange={e=>setName(e.target.value)}/></label><div className="sharing-grid"><label>总电力<input type="number" min="0.01" max={p.budgetMicros/1e6} step="0.01" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label>单次电力<input type="number" min="0.01" max={Math.min(budget,p.perRunMicros/1e6)} step="0.01" value={perRun} onChange={e=>setPerRun(Number(e.target.value))}/></label><label>有效天数<input type="number" min="1" max="90" value={days} onChange={e=>setDays(Number(e.target.value))}/></label></div><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>我授权外部程序使用此分身，承担限额内的费用。</label><button type="button" disabled={busy||!name.trim()||!confirmed} onClick={()=>void issue()}>生成独立 API 密钥</button>{token?<div><p>密钥只展示这一次，请保存。</p><input readOnly aria-label="新 API 密钥" value={token}/><button type="button" onClick={()=>void navigator.clipboard.writeText(token).catch(()=>setMessage('请手动复制密钥'))}>复制</button><button type="button" onClick={()=>setToken('')}>已保存，隐藏</button></div>:null}{items.map(g=><details key={g.id}><summary>{g.name} · v{g.version} · {g.status==='active'?'有效':'已撤销'}</summary><p>已用 {power(g.spent)} / {power(g.budgetMicros)} 电力 · 到期 {new Date(g.expiresAt).toLocaleString()}</p>{g.status==='active'?<button type="button" disabled={busy} onClick={()=>void revoke(g.id)}>撤销密钥</button>:null}</details>)}<Pagination page={page} size={5} total={total} onChange={setPage}/><details><summary>程序调用方法</summary><p>POST {location.origin}/api/v1/tasks</p><pre style={{whiteSpace:'pre-wrap',overflowWrap:'anywhere'}}>{'Authorization: Bearer 你的API密钥\nContent-Type: application/json\n\n{"operationId":"example-request-0001","question":"要问的问题"}'}</pre><p>保存返回的 task.id，通过 GET /api/v1/tasks/任务编号 查询。相同 operationId 重试会找回原任务；更换问题应使用新编号。</p></details></details><SponsorshipPanel api={api} id={p.id}/><EarningsPanel api={api} id={p.id}/>{message?<p role="status">{message}</p>:null}</div>;
}
function SponsorshipPanel({api,id}:{api:typeof Api;id:string}){
  const [page,setPage]=useState(1),[username,setUsername]=useState(''),[budget,setBudget]=useState(1),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[data,setData]=useState<{items:{id:string;name:string;status:string;budgetMicros:number;usedMicros:number}[];total:number}>({items:[],total:0});
  async function load(){try{setData(await api<typeof data>(`/api/sharing-commerce/manage/${id}/sponsorships?page=${page}`));}catch(e){setMessage(e instanceof Error?e.message:'加载失败');}}
  useEffect(()=>{void load();},[api,id,page]);
  async function act(grantId?:string){setBusy(true);setMessage('');try{await api(`/api/sharing-commerce/manage/${id}/sponsorships${grantId?`/${grantId}/revoke`:''}`,{method:'POST',body:JSON.stringify({username,budget,confirmed})});setConfirmed(false);await load();}catch(e){setMessage(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
  return <details><summary>给指定访客赠送使用额度</summary><p className="hint">填写对方已注册的账号。额度只用于本分身，你承担实际消耗，不向对方钱包充钱。有限定访问账号时，还要把对方加入允许名单。</p><label>访客账号<input maxLength={64} value={username} onChange={e=>setUsername(e.target.value)}/></label><label>使用额度（电力）<input type="number" min="0.01" step="0.01" value={budget} onChange={e=>setBudget(Number(e.target.value))}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>确认由我承担这份额度内的实际费用</label><button type="button" disabled={busy||!confirmed||!username.trim()} onClick={()=>void act()}>赠送使用额度</button>{data.items.map(g=><details key={g.id}><summary>{g.name} · {g.status==='active'?'使用中':'已撤销'}</summary><p>{power(g.usedMicros)} / {power(g.budgetMicros)} 电力（含预留）</p>{g.status==='active'?<button type="button" disabled={busy} onClick={()=>void act(g.id)}>撤销赠送</button>:null}</details>)}<Pagination page={page} size={5} total={data.total} onChange={setPage}/>{message?<p role="status">{message}</p>:null}</details>;
}
function EarningsPanel({api,id}:{api:typeof Api;id:string}){
  const [page,setPage]=useState(1),[data,setData]=useState<{total:number;pendingRevenueMicros:number;items:{id:string;createdAt:string;status:string;model:string;visitorChargeMicros:number;platformFeeMicros:number;publisherRevenueMicros:number;bonusMicros:number}[]}>(),[error,setError]=useState('');
  useEffect(()=>{let live=true;void api<typeof data>(`/api/sharing-commerce/manage/${id}/earnings?page=${page}`).then(d=>{if(live)setData(d);}).catch(e=>{if(live)setError(e.message);});return()=>{live=false;};},[api,id,page]);
  return <details><summary>收益账本 · {power(data?.pendingRevenueMicros??0)} 电力待结算</summary><p className="hint">收益在实际消费后形成，赠送消耗不产生收益。暂不提现，也不自动转入可消费余额。</p>{data?.items.map(r=><details key={r.id}><summary>{new Date(r.createdAt).toLocaleString()} · {r.model} · 收益 {power(r.publisherRevenueMicros)} 电力</summary><p>访客消耗 {power(r.visitorChargeMicros)} · ONE 基础费用 {power(r.platformFeeMicros)} · 赠送部分 {power(r.bonusMicros)} 电力</p></details>)}{data?<Pagination page={page} total={data.total} onChange={setPage}/>:null}{error?<p role="alert">{error}</p>:null}</details>;
}
export function PublicCommercePolicyPanel({api}:{api:typeof Api}){
  const [policy,setPolicy]=useState<{revision:number;visitorPaymentsEnabled:boolean;publisherShareBps:number}>(),[share,setShare]=useState(100),[enabled,setEnabled]=useState(false),[confirmed,setConfirmed]=useState(false),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
  useEffect(()=>{let live=true;void api<typeof policy>('/api/admin/public-commerce').then(p=>{if(live&&p){setPolicy(p);setShare(p.publisherShareBps/100);setEnabled(p.visitorPaymentsEnabled);}}).catch(e=>{if(live)setMessage(e.message);});return()=>{live=false;};},[api]);
  async function save(){setBusy(true);try{const p=await api<NonNullable<typeof policy>>('/api/admin/public-commerce',{method:'POST',body:JSON.stringify({revision:policy?.revision,visitorPaymentsEnabled:enabled,publisherSharePercent:share,confirmed})});setPolicy(p);setConfirmed(false);setMessage('已保存，收益比例适用于新任务。现有分身的收费百分比需主人自行配置。');}catch(e){setMessage(e instanceof Error?e.message:'保存失败');}finally{setBusy(false);}}
  return <details><summary>访客付费与收益政策 · {policy?.visitorPaymentsEnabled?'已启用':'未启用'}</summary><p className="hint">发布者设置 120% 时，访客消费为 ONE 基础费用的 1.2 倍；加价部分再按这里的比例分配。只有充值本金支付的部分产生收益。</p><label><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>启用访客自付</label><label>发布者分得加价收益的百分比<input type="number" min="0" max="100" step="1" value={share} onChange={e=>setShare(Number(e.target.value))}/></label><label><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>确认新的计费政策</label><button type="button" disabled={busy||!policy||!confirmed} onClick={()=>void save()}>保存政策</button>{message?<p role="status">{message}</p>:null}</details>;
}
